add_subdirectory(TestPersonalLib)
add_subdirectory(TestMD5)
add_subdirectory(TestClient)
add_subdirectory(TestServer)

#add_subdirectory(TestCtpTraderApi)
#add_subdirectory(TestCtpMdApi)
if(CMAKE_SYSTEM_NAME MATCHES "Windows")
#	add_subdirectory(TestThrift)
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
endif()
