/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef account_TYPES_H
#define account_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class ListAccountRequest;

class AccountInfo;

class ListAccountResponse;

typedef struct _ListAccountRequest__isset {
  _ListAccountRequest__isset() : unitName(false) {}
  bool unitName :1;
} _ListAccountRequest__isset;

class ListAccountRequest : public virtual ::apache::thrift::TBase {
 public:

  ListAccountRequest(const ListAccountRequest&);
  ListAccountRequest& operator=(const ListAccountRequest&);
  ListAccountRequest() noexcept;

  virtual ~ListAccountRequest() noexcept;
  std::string unitName;

  _ListAccountRequest__isset __isset;

  void __set_unitName(const std::string& val);

  bool operator == (const ListAccountRequest & rhs) const;
  bool operator != (const ListAccountRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListAccountRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListAccountRequest &a, ListAccountRequest &b);

std::ostream& operator<<(std::ostream& out, const ListAccountRequest& obj);

typedef struct _AccountInfo__isset {
  _AccountInfo__isset() : tradeFundName(false), exchange(false), accountName(false) {}
  bool tradeFundName :1;
  bool exchange :1;
  bool accountName :1;
} _AccountInfo__isset;

class AccountInfo : public virtual ::apache::thrift::TBase {
 public:

  AccountInfo(const AccountInfo&);
  AccountInfo& operator=(const AccountInfo&);
  AccountInfo() noexcept;

  virtual ~AccountInfo() noexcept;
  std::string tradeFundName;
  std::string exchange;
  std::string accountName;

  _AccountInfo__isset __isset;

  void __set_tradeFundName(const std::string& val);

  void __set_exchange(const std::string& val);

  void __set_accountName(const std::string& val);

  bool operator == (const AccountInfo & rhs) const;
  bool operator != (const AccountInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AccountInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AccountInfo &a, AccountInfo &b);

std::ostream& operator<<(std::ostream& out, const AccountInfo& obj);

typedef struct _ListAccountResponse__isset {
  _ListAccountResponse__isset() : status(false), detail(false), unitName(false), topics(false), accounts(false) {}
  bool status :1;
  bool detail :1;
  bool unitName :1;
  bool topics :1;
  bool accounts :1;
} _ListAccountResponse__isset;

class ListAccountResponse : public virtual ::apache::thrift::TBase {
 public:

  ListAccountResponse(const ListAccountResponse&);
  ListAccountResponse& operator=(const ListAccountResponse&);
  ListAccountResponse() noexcept;

  virtual ~ListAccountResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string unitName;
  std::map<std::string, int32_t>  topics;
  std::vector<AccountInfo>  accounts;

  _ListAccountResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_unitName(const std::string& val);

  void __set_topics(const std::map<std::string, int32_t> & val);

  void __set_accounts(const std::vector<AccountInfo> & val);

  bool operator == (const ListAccountResponse & rhs) const;
  bool operator != (const ListAccountResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListAccountResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListAccountResponse &a, ListAccountResponse &b);

std::ostream& operator<<(std::ostream& out, const ListAccountResponse& obj);



#endif
