/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "account_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




ListAccountRequest::~ListAccountRequest() noexcept {
}

ListAccountRequest::ListAccountRequest() noexcept
   : unitName() {
}

void ListAccountRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}
std::ostream& operator<<(std::ostream& out, const ListAccountRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListAccountRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListAccountRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListAccountRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListAccountRequest &a, ListAccountRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.__isset, b.__isset);
}

bool ListAccountRequest::operator==(const ListAccountRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  return true;
}

ListAccountRequest::ListAccountRequest(const ListAccountRequest& other0) {
  unitName = other0.unitName;
  __isset = other0.__isset;
}
ListAccountRequest& ListAccountRequest::operator=(const ListAccountRequest& other1) {
  unitName = other1.unitName;
  __isset = other1.__isset;
  return *this;
}
void ListAccountRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListAccountRequest(";
  out << "unitName=" << to_string(unitName);
  out << ")";
}


AccountInfo::~AccountInfo() noexcept {
}

AccountInfo::AccountInfo() noexcept
   : tradeFundName(),
     exchange(),
     accountName() {
}

void AccountInfo::__set_tradeFundName(const std::string& val) {
  this->tradeFundName = val;
}

void AccountInfo::__set_exchange(const std::string& val) {
  this->exchange = val;
}

void AccountInfo::__set_accountName(const std::string& val) {
  this->accountName = val;
}
std::ostream& operator<<(std::ostream& out, const AccountInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AccountInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->tradeFundName);
          this->__isset.tradeFundName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->exchange);
          this->__isset.exchange = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->accountName);
          this->__isset.accountName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AccountInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AccountInfo");

  xfer += oprot->writeFieldBegin("tradeFundName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->tradeFundName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("exchange", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->exchange);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("accountName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->accountName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AccountInfo &a, AccountInfo &b) {
  using ::std::swap;
  swap(a.tradeFundName, b.tradeFundName);
  swap(a.exchange, b.exchange);
  swap(a.accountName, b.accountName);
  swap(a.__isset, b.__isset);
}

bool AccountInfo::operator==(const AccountInfo & rhs) const
{
  if (!(tradeFundName == rhs.tradeFundName))
    return false;
  if (!(exchange == rhs.exchange))
    return false;
  if (!(accountName == rhs.accountName))
    return false;
  return true;
}

AccountInfo::AccountInfo(const AccountInfo& other2) {
  tradeFundName = other2.tradeFundName;
  exchange = other2.exchange;
  accountName = other2.accountName;
  __isset = other2.__isset;
}
AccountInfo& AccountInfo::operator=(const AccountInfo& other3) {
  tradeFundName = other3.tradeFundName;
  exchange = other3.exchange;
  accountName = other3.accountName;
  __isset = other3.__isset;
  return *this;
}
void AccountInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AccountInfo(";
  out << "tradeFundName=" << to_string(tradeFundName);
  out << ", " << "exchange=" << to_string(exchange);
  out << ", " << "accountName=" << to_string(accountName);
  out << ")";
}


ListAccountResponse::~ListAccountResponse() noexcept {
}

ListAccountResponse::ListAccountResponse() noexcept
   : status(0),
     detail(),
     unitName() {
}

void ListAccountResponse::__set_status(const int32_t val) {
  this->status = val;
}

void ListAccountResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void ListAccountResponse::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void ListAccountResponse::__set_topics(const std::map<std::string, int32_t> & val) {
  this->topics = val;
}

void ListAccountResponse::__set_accounts(const std::vector<AccountInfo> & val) {
  this->accounts = val;
}
std::ostream& operator<<(std::ostream& out, const ListAccountResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListAccountResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->topics.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _ktype5;
            ::apache::thrift::protocol::TType _vtype6;
            xfer += iprot->readMapBegin(_ktype5, _vtype6, _size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              std::string _key9;
              xfer += iprot->readString(_key9);
              int32_t& _val10 = this->topics[_key9];
              xfer += iprot->readI32(_val10);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.topics = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->accounts.clear();
            uint32_t _size11;
            ::apache::thrift::protocol::TType _etype14;
            xfer += iprot->readListBegin(_etype14, _size11);
            this->accounts.resize(_size11);
            uint32_t _i15;
            for (_i15 = 0; _i15 < _size11; ++_i15)
            {
              xfer += this->accounts[_i15].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.accounts = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListAccountResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListAccountResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("topics", ::apache::thrift::protocol::T_MAP, 4);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->topics.size()));
    std::map<std::string, int32_t> ::const_iterator _iter16;
    for (_iter16 = this->topics.begin(); _iter16 != this->topics.end(); ++_iter16)
    {
      xfer += oprot->writeString(_iter16->first);
      xfer += oprot->writeI32(_iter16->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("accounts", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->accounts.size()));
    std::vector<AccountInfo> ::const_iterator _iter17;
    for (_iter17 = this->accounts.begin(); _iter17 != this->accounts.end(); ++_iter17)
    {
      xfer += (*_iter17).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListAccountResponse &a, ListAccountResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.unitName, b.unitName);
  swap(a.topics, b.topics);
  swap(a.accounts, b.accounts);
  swap(a.__isset, b.__isset);
}

bool ListAccountResponse::operator==(const ListAccountResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(unitName == rhs.unitName))
    return false;
  if (!(topics == rhs.topics))
    return false;
  if (!(accounts == rhs.accounts))
    return false;
  return true;
}

ListAccountResponse::ListAccountResponse(const ListAccountResponse& other18) {
  status = other18.status;
  detail = other18.detail;
  unitName = other18.unitName;
  topics = other18.topics;
  accounts = other18.accounts;
  __isset = other18.__isset;
}
ListAccountResponse& ListAccountResponse::operator=(const ListAccountResponse& other19) {
  status = other19.status;
  detail = other19.detail;
  unitName = other19.unitName;
  topics = other19.topics;
  accounts = other19.accounts;
  __isset = other19.__isset;
  return *this;
}
void ListAccountResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListAccountResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "unitName=" << to_string(unitName);
  out << ", " << "topics=" << to_string(topics);
  out << ", " << "accounts=" << to_string(accounts);
  out << ")";
}


