/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "account_constants.h"



const accountConstants g_account_constants;

accountConstants::accountConstants() {
  WMESSAGE_MONITOR_LIST_ACCOUNT = 8193;

}



