/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef account_CONSTANTS_H
#define account_CONSTANTS_H

#include "account_types.h"



class accountConstants {
 public:
  accountConstants();

  int32_t WMESSAGE_MONITOR_LIST_ACCOUNT;
};

extern const accountConstants g_account_constants;



#endif
