/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef common_TYPES_H
#define common_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class HeartbeatRequest;

class HeartbeatResponse;

class CheckTokenRequest;

class CheckTokenResponse;

typedef struct _HeartbeatRequest__isset {
  _HeartbeatRequest__isset() : timestamp(false) {}
  bool timestamp :1;
} _HeartbeatRequest__isset;

class HeartbeatRequest : public virtual ::apache::thrift::TBase {
 public:

  HeartbeatRequest(const HeartbeatRequest&) noexcept;
  HeartbeatRequest& operator=(const HeartbeatRequest&) noexcept;
  HeartbeatRequest() noexcept;

  virtual ~HeartbeatRequest() noexcept;
  int64_t timestamp;

  _HeartbeatRequest__isset __isset;

  void __set_timestamp(const int64_t val);

  bool operator == (const HeartbeatRequest & rhs) const;
  bool operator != (const HeartbeatRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HeartbeatRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HeartbeatRequest &a, HeartbeatRequest &b);

std::ostream& operator<<(std::ostream& out, const HeartbeatRequest& obj);

typedef struct _HeartbeatResponse__isset {
  _HeartbeatResponse__isset() : timestamp(false) {}
  bool timestamp :1;
} _HeartbeatResponse__isset;

class HeartbeatResponse : public virtual ::apache::thrift::TBase {
 public:

  HeartbeatResponse(const HeartbeatResponse&) noexcept;
  HeartbeatResponse& operator=(const HeartbeatResponse&) noexcept;
  HeartbeatResponse() noexcept;

  virtual ~HeartbeatResponse() noexcept;
  int64_t timestamp;

  _HeartbeatResponse__isset __isset;

  void __set_timestamp(const int64_t val);

  bool operator == (const HeartbeatResponse & rhs) const;
  bool operator != (const HeartbeatResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HeartbeatResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HeartbeatResponse &a, HeartbeatResponse &b);

std::ostream& operator<<(std::ostream& out, const HeartbeatResponse& obj);

typedef struct _CheckTokenRequest__isset {
  _CheckTokenRequest__isset() : token(false) {}
  bool token :1;
} _CheckTokenRequest__isset;

class CheckTokenRequest : public virtual ::apache::thrift::TBase {
 public:

  CheckTokenRequest(const CheckTokenRequest&);
  CheckTokenRequest& operator=(const CheckTokenRequest&);
  CheckTokenRequest() noexcept;

  virtual ~CheckTokenRequest() noexcept;
  std::string token;

  _CheckTokenRequest__isset __isset;

  void __set_token(const std::string& val);

  bool operator == (const CheckTokenRequest & rhs) const;
  bool operator != (const CheckTokenRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CheckTokenRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CheckTokenRequest &a, CheckTokenRequest &b);

std::ostream& operator<<(std::ostream& out, const CheckTokenRequest& obj);

typedef struct _CheckTokenResponse__isset {
  _CheckTokenResponse__isset() : status(false), detail(false), token(false), permissions(false) {}
  bool status :1;
  bool detail :1;
  bool token :1;
  bool permissions :1;
} _CheckTokenResponse__isset;

class CheckTokenResponse : public virtual ::apache::thrift::TBase {
 public:

  CheckTokenResponse(const CheckTokenResponse&);
  CheckTokenResponse& operator=(const CheckTokenResponse&);
  CheckTokenResponse() noexcept;

  virtual ~CheckTokenResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string token;
  std::vector<std::string>  permissions;

  _CheckTokenResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_token(const std::string& val);

  void __set_permissions(const std::vector<std::string> & val);

  bool operator == (const CheckTokenResponse & rhs) const;
  bool operator != (const CheckTokenResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CheckTokenResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CheckTokenResponse &a, CheckTokenResponse &b);

std::ostream& operator<<(std::ostream& out, const CheckTokenResponse& obj);



#endif
