/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef instrument_TYPES_H
#define instrument_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class ListInstrumentRequest;

class InstrumentInfo;

class ListInstrumentResponse;

class ListUnitInstrumentRequest;

class ListUnitInstrumentResponse;

typedef struct _ListInstrumentRequest__isset {
  _ListInstrumentRequest__isset() : prodMat(false) {}
  bool prodMat :1;
} _ListInstrumentRequest__isset;

class ListInstrumentRequest : public virtual ::apache::thrift::TBase {
 public:

  ListInstrumentRequest(const ListInstrumentRequest&);
  ListInstrumentRequest& operator=(const ListInstrumentRequest&);
  ListInstrumentRequest() noexcept;

  virtual ~ListInstrumentRequest() noexcept;
  std::string prodMat;

  _ListInstrumentRequest__isset __isset;

  void __set_prodMat(const std::string& val);

  bool operator == (const ListInstrumentRequest & rhs) const;
  bool operator != (const ListInstrumentRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListInstrumentRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListInstrumentRequest &a, ListInstrumentRequest &b);

std::ostream& operator<<(std::ostream& out, const ListInstrumentRequest& obj);

typedef struct _InstrumentInfo__isset {
  _InstrumentInfo__isset() : name(false), type(false), underlying(false), multiplier(false), strike(false), tickSize(false), expiration(false) {}
  bool name :1;
  bool type :1;
  bool underlying :1;
  bool multiplier :1;
  bool strike :1;
  bool tickSize :1;
  bool expiration :1;
} _InstrumentInfo__isset;

class InstrumentInfo : public virtual ::apache::thrift::TBase {
 public:

  InstrumentInfo(const InstrumentInfo&);
  InstrumentInfo& operator=(const InstrumentInfo&);
  InstrumentInfo() noexcept;

  virtual ~InstrumentInfo() noexcept;
  std::string name;
  std::string type;
  std::string underlying;
  double multiplier;
  double strike;
  double tickSize;
  int64_t expiration;

  _InstrumentInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_type(const std::string& val);

  void __set_underlying(const std::string& val);

  void __set_multiplier(const double val);

  void __set_strike(const double val);

  void __set_tickSize(const double val);

  void __set_expiration(const int64_t val);

  bool operator == (const InstrumentInfo & rhs) const;
  bool operator != (const InstrumentInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InstrumentInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InstrumentInfo &a, InstrumentInfo &b);

std::ostream& operator<<(std::ostream& out, const InstrumentInfo& obj);

typedef struct _ListInstrumentResponse__isset {
  _ListInstrumentResponse__isset() : status(false), detail(false), name(false), instruments(false) {}
  bool status :1;
  bool detail :1;
  bool name :1;
  bool instruments :1;
} _ListInstrumentResponse__isset;

class ListInstrumentResponse : public virtual ::apache::thrift::TBase {
 public:

  ListInstrumentResponse(const ListInstrumentResponse&);
  ListInstrumentResponse& operator=(const ListInstrumentResponse&);
  ListInstrumentResponse() noexcept;

  virtual ~ListInstrumentResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string name;
  std::vector<InstrumentInfo>  instruments;

  _ListInstrumentResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_name(const std::string& val);

  void __set_instruments(const std::vector<InstrumentInfo> & val);

  bool operator == (const ListInstrumentResponse & rhs) const;
  bool operator != (const ListInstrumentResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListInstrumentResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListInstrumentResponse &a, ListInstrumentResponse &b);

std::ostream& operator<<(std::ostream& out, const ListInstrumentResponse& obj);

typedef struct _ListUnitInstrumentRequest__isset {
  _ListUnitInstrumentRequest__isset() : unitName(false) {}
  bool unitName :1;
} _ListUnitInstrumentRequest__isset;

class ListUnitInstrumentRequest : public virtual ::apache::thrift::TBase {
 public:

  ListUnitInstrumentRequest(const ListUnitInstrumentRequest&);
  ListUnitInstrumentRequest& operator=(const ListUnitInstrumentRequest&);
  ListUnitInstrumentRequest() noexcept;

  virtual ~ListUnitInstrumentRequest() noexcept;
  std::string unitName;

  _ListUnitInstrumentRequest__isset __isset;

  void __set_unitName(const std::string& val);

  bool operator == (const ListUnitInstrumentRequest & rhs) const;
  bool operator != (const ListUnitInstrumentRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListUnitInstrumentRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListUnitInstrumentRequest &a, ListUnitInstrumentRequest &b);

std::ostream& operator<<(std::ostream& out, const ListUnitInstrumentRequest& obj);

typedef struct _ListUnitInstrumentResponse__isset {
  _ListUnitInstrumentResponse__isset() : status(false), detail(false), instruments(false) {}
  bool status :1;
  bool detail :1;
  bool instruments :1;
} _ListUnitInstrumentResponse__isset;

class ListUnitInstrumentResponse : public virtual ::apache::thrift::TBase {
 public:

  ListUnitInstrumentResponse(const ListUnitInstrumentResponse&);
  ListUnitInstrumentResponse& operator=(const ListUnitInstrumentResponse&);
  ListUnitInstrumentResponse() noexcept;

  virtual ~ListUnitInstrumentResponse() noexcept;
  int32_t status;
  std::string detail;
  std::vector<InstrumentInfo>  instruments;

  _ListUnitInstrumentResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_instruments(const std::vector<InstrumentInfo> & val);

  bool operator == (const ListUnitInstrumentResponse & rhs) const;
  bool operator != (const ListUnitInstrumentResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListUnitInstrumentResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListUnitInstrumentResponse &a, ListUnitInstrumentResponse &b);

std::ostream& operator<<(std::ostream& out, const ListUnitInstrumentResponse& obj);



#endif
