/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "liveparam_constants.h"



const liveparamConstants g_liveparam_constants;

liveparamConstants::liveparamConstants() {
  WMESSAGE_LIVEPARAMGROUP_LIST = 2049;

  WMESSAGE_LIVEPARAM_SET = 2050;

}



