/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef liveparam_CONSTANTS_H
#define liveparam_CONSTANTS_H

#include "liveparam_types.h"



class liveparamConstants {
 public:
  liveparamConstants();

  int32_t WMESSAGE_LIVEPARAMGROUP_LIST;
  int32_t WMESSAGE_LIVEPARAM_SET;
};

extern const liveparamConstants g_liveparam_constants;



#endif
