/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef liveparam_TYPES_H
#define liveparam_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "topic_types.h"




class LiveParamGroupListRequest;

class LiveParamInfo;

class LiveParamGroupInfo;

class LiveParamGroupListResponse;

class LiveParamSetRequest;

class LiveParamSetResponse;

typedef struct _LiveParamGroupListRequest__isset {
  _LiveParamGroupListRequest__isset() : unitName(false) {}
  bool unitName :1;
} _LiveParamGroupListRequest__isset;

class LiveParamGroupListRequest : public virtual ::apache::thrift::TBase {
 public:

  LiveParamGroupListRequest(const LiveParamGroupListRequest&);
  LiveParamGroupListRequest& operator=(const LiveParamGroupListRequest&);
  LiveParamGroupListRequest() noexcept;

  virtual ~LiveParamGroupListRequest() noexcept;
  std::string unitName;

  _LiveParamGroupListRequest__isset __isset;

  void __set_unitName(const std::string& val);

  bool operator == (const LiveParamGroupListRequest & rhs) const;
  bool operator != (const LiveParamGroupListRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamGroupListRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamGroupListRequest &a, LiveParamGroupListRequest &b);

std::ostream& operator<<(std::ostream& out, const LiveParamGroupListRequest& obj);

typedef struct _LiveParamInfo__isset {
  _LiveParamInfo__isset() : type(false), name(false), value(false) {}
  bool type :1;
  bool name :1;
  bool value :1;
} _LiveParamInfo__isset;

class LiveParamInfo : public virtual ::apache::thrift::TBase {
 public:

  LiveParamInfo(const LiveParamInfo&);
  LiveParamInfo& operator=(const LiveParamInfo&);
  LiveParamInfo() noexcept;

  virtual ~LiveParamInfo() noexcept;
  std::string type;
  std::string name;
  std::string value;

  _LiveParamInfo__isset __isset;

  void __set_type(const std::string& val);

  void __set_name(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const LiveParamInfo & rhs) const;
  bool operator != (const LiveParamInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamInfo &a, LiveParamInfo &b);

std::ostream& operator<<(std::ostream& out, const LiveParamInfo& obj);

typedef struct _LiveParamGroupInfo__isset {
  _LiveParamGroupInfo__isset() : name(false), params(false), enums(false) {}
  bool name :1;
  bool params :1;
  bool enums :1;
} _LiveParamGroupInfo__isset;

class LiveParamGroupInfo : public virtual ::apache::thrift::TBase {
 public:

  LiveParamGroupInfo(const LiveParamGroupInfo&);
  LiveParamGroupInfo& operator=(const LiveParamGroupInfo&);
  LiveParamGroupInfo() noexcept;

  virtual ~LiveParamGroupInfo() noexcept;
  std::string name;
  std::vector<LiveParamInfo>  params;
  std::map<std::string,  ::EnumDesc>  enums;

  _LiveParamGroupInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_params(const std::vector<LiveParamInfo> & val);

  void __set_enums(const std::map<std::string,  ::EnumDesc> & val);

  bool operator == (const LiveParamGroupInfo & rhs) const;
  bool operator != (const LiveParamGroupInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamGroupInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamGroupInfo &a, LiveParamGroupInfo &b);

std::ostream& operator<<(std::ostream& out, const LiveParamGroupInfo& obj);

typedef struct _LiveParamGroupListResponse__isset {
  _LiveParamGroupListResponse__isset() : status(false), detail(false), unitName(false), groups(false) {}
  bool status :1;
  bool detail :1;
  bool unitName :1;
  bool groups :1;
} _LiveParamGroupListResponse__isset;

class LiveParamGroupListResponse : public virtual ::apache::thrift::TBase {
 public:

  LiveParamGroupListResponse(const LiveParamGroupListResponse&);
  LiveParamGroupListResponse& operator=(const LiveParamGroupListResponse&);
  LiveParamGroupListResponse() noexcept;

  virtual ~LiveParamGroupListResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string unitName;
  std::vector<LiveParamGroupInfo>  groups;

  _LiveParamGroupListResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_unitName(const std::string& val);

  void __set_groups(const std::vector<LiveParamGroupInfo> & val);

  bool operator == (const LiveParamGroupListResponse & rhs) const;
  bool operator != (const LiveParamGroupListResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamGroupListResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamGroupListResponse &a, LiveParamGroupListResponse &b);

std::ostream& operator<<(std::ostream& out, const LiveParamGroupListResponse& obj);

typedef struct _LiveParamSetRequest__isset {
  _LiveParamSetRequest__isset() : unitName(false), grpName(false), params(false) {}
  bool unitName :1;
  bool grpName :1;
  bool params :1;
} _LiveParamSetRequest__isset;

class LiveParamSetRequest : public virtual ::apache::thrift::TBase {
 public:

  LiveParamSetRequest(const LiveParamSetRequest&);
  LiveParamSetRequest& operator=(const LiveParamSetRequest&);
  LiveParamSetRequest() noexcept;

  virtual ~LiveParamSetRequest() noexcept;
  std::string unitName;
  std::string grpName;
  std::map<std::string, std::string>  params;

  _LiveParamSetRequest__isset __isset;

  void __set_unitName(const std::string& val);

  void __set_grpName(const std::string& val);

  void __set_params(const std::map<std::string, std::string> & val);

  bool operator == (const LiveParamSetRequest & rhs) const;
  bool operator != (const LiveParamSetRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamSetRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamSetRequest &a, LiveParamSetRequest &b);

std::ostream& operator<<(std::ostream& out, const LiveParamSetRequest& obj);

typedef struct _LiveParamSetResponse__isset {
  _LiveParamSetResponse__isset() : status(false), detail(false), unitName(false) {}
  bool status :1;
  bool detail :1;
  bool unitName :1;
} _LiveParamSetResponse__isset;

class LiveParamSetResponse : public virtual ::apache::thrift::TBase {
 public:

  LiveParamSetResponse(const LiveParamSetResponse&);
  LiveParamSetResponse& operator=(const LiveParamSetResponse&);
  LiveParamSetResponse() noexcept;

  virtual ~LiveParamSetResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string unitName;

  _LiveParamSetResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_unitName(const std::string& val);

  bool operator == (const LiveParamSetResponse & rhs) const;
  bool operator != (const LiveParamSetResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LiveParamSetResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LiveParamSetResponse &a, LiveParamSetResponse &b);

std::ostream& operator<<(std::ostream& out, const LiveParamSetResponse& obj);



#endif
