/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "liveparam_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




LiveParamGroupListRequest::~LiveParamGroupListRequest() noexcept {
}

LiveParamGroupListRequest::LiveParamGroupListRequest() noexcept
   : unitName() {
}

void LiveParamGroupListRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamGroupListRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamGroupListRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamGroupListRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamGroupListRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamGroupListRequest &a, LiveParamGroupListRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.__isset, b.__isset);
}

bool LiveParamGroupListRequest::operator==(const LiveParamGroupListRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  return true;
}

LiveParamGroupListRequest::LiveParamGroupListRequest(const LiveParamGroupListRequest& other0) {
  unitName = other0.unitName;
  __isset = other0.__isset;
}
LiveParamGroupListRequest& LiveParamGroupListRequest::operator=(const LiveParamGroupListRequest& other1) {
  unitName = other1.unitName;
  __isset = other1.__isset;
  return *this;
}
void LiveParamGroupListRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamGroupListRequest(";
  out << "unitName=" << to_string(unitName);
  out << ")";
}


LiveParamInfo::~LiveParamInfo() noexcept {
}

LiveParamInfo::LiveParamInfo() noexcept
   : type(),
     name(),
     value() {
}

void LiveParamInfo::__set_type(const std::string& val) {
  this->type = val;
}

void LiveParamInfo::__set_name(const std::string& val) {
  this->name = val;
}

void LiveParamInfo::__set_value(const std::string& val) {
  this->value = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->type);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->value);
          this->__isset.value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamInfo");

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamInfo &a, LiveParamInfo &b) {
  using ::std::swap;
  swap(a.type, b.type);
  swap(a.name, b.name);
  swap(a.value, b.value);
  swap(a.__isset, b.__isset);
}

bool LiveParamInfo::operator==(const LiveParamInfo & rhs) const
{
  if (!(type == rhs.type))
    return false;
  if (!(name == rhs.name))
    return false;
  if (!(value == rhs.value))
    return false;
  return true;
}

LiveParamInfo::LiveParamInfo(const LiveParamInfo& other2) {
  type = other2.type;
  name = other2.name;
  value = other2.value;
  __isset = other2.__isset;
}
LiveParamInfo& LiveParamInfo::operator=(const LiveParamInfo& other3) {
  type = other3.type;
  name = other3.name;
  value = other3.value;
  __isset = other3.__isset;
  return *this;
}
void LiveParamInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamInfo(";
  out << "type=" << to_string(type);
  out << ", " << "name=" << to_string(name);
  out << ", " << "value=" << to_string(value);
  out << ")";
}


LiveParamGroupInfo::~LiveParamGroupInfo() noexcept {
}

LiveParamGroupInfo::LiveParamGroupInfo() noexcept
   : name() {
}

void LiveParamGroupInfo::__set_name(const std::string& val) {
  this->name = val;
}

void LiveParamGroupInfo::__set_params(const std::vector<LiveParamInfo> & val) {
  this->params = val;
}

void LiveParamGroupInfo::__set_enums(const std::map<std::string,  ::EnumDesc> & val) {
  this->enums = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamGroupInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamGroupInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->params.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->params.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->params[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.params = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->enums.clear();
            uint32_t _size9;
            ::apache::thrift::protocol::TType _ktype10;
            ::apache::thrift::protocol::TType _vtype11;
            xfer += iprot->readMapBegin(_ktype10, _vtype11, _size9);
            uint32_t _i13;
            for (_i13 = 0; _i13 < _size9; ++_i13)
            {
              std::string _key14;
              xfer += iprot->readString(_key14);
               ::EnumDesc& _val15 = this->enums[_key14];
              xfer += _val15.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.enums = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamGroupInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamGroupInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("params", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->params.size()));
    std::vector<LiveParamInfo> ::const_iterator _iter16;
    for (_iter16 = this->params.begin(); _iter16 != this->params.end(); ++_iter16)
    {
      xfer += (*_iter16).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("enums", ::apache::thrift::protocol::T_MAP, 3);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->enums.size()));
    std::map<std::string,  ::EnumDesc> ::const_iterator _iter17;
    for (_iter17 = this->enums.begin(); _iter17 != this->enums.end(); ++_iter17)
    {
      xfer += oprot->writeString(_iter17->first);
      xfer += _iter17->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamGroupInfo &a, LiveParamGroupInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.params, b.params);
  swap(a.enums, b.enums);
  swap(a.__isset, b.__isset);
}

bool LiveParamGroupInfo::operator==(const LiveParamGroupInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(params == rhs.params))
    return false;
  if (!(enums == rhs.enums))
    return false;
  return true;
}

LiveParamGroupInfo::LiveParamGroupInfo(const LiveParamGroupInfo& other18) {
  name = other18.name;
  params = other18.params;
  enums = other18.enums;
  __isset = other18.__isset;
}
LiveParamGroupInfo& LiveParamGroupInfo::operator=(const LiveParamGroupInfo& other19) {
  name = other19.name;
  params = other19.params;
  enums = other19.enums;
  __isset = other19.__isset;
  return *this;
}
void LiveParamGroupInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamGroupInfo(";
  out << "name=" << to_string(name);
  out << ", " << "params=" << to_string(params);
  out << ", " << "enums=" << to_string(enums);
  out << ")";
}


LiveParamGroupListResponse::~LiveParamGroupListResponse() noexcept {
}

LiveParamGroupListResponse::LiveParamGroupListResponse() noexcept
   : status(0),
     detail(),
     unitName() {
}

void LiveParamGroupListResponse::__set_status(const int32_t val) {
  this->status = val;
}

void LiveParamGroupListResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void LiveParamGroupListResponse::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void LiveParamGroupListResponse::__set_groups(const std::vector<LiveParamGroupInfo> & val) {
  this->groups = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamGroupListResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamGroupListResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->groups.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readListBegin(_etype23, _size20);
            this->groups.resize(_size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              xfer += this->groups[_i24].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.groups = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamGroupListResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamGroupListResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("groups", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->groups.size()));
    std::vector<LiveParamGroupInfo> ::const_iterator _iter25;
    for (_iter25 = this->groups.begin(); _iter25 != this->groups.end(); ++_iter25)
    {
      xfer += (*_iter25).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamGroupListResponse &a, LiveParamGroupListResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.unitName, b.unitName);
  swap(a.groups, b.groups);
  swap(a.__isset, b.__isset);
}

bool LiveParamGroupListResponse::operator==(const LiveParamGroupListResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(unitName == rhs.unitName))
    return false;
  if (!(groups == rhs.groups))
    return false;
  return true;
}

LiveParamGroupListResponse::LiveParamGroupListResponse(const LiveParamGroupListResponse& other26) {
  status = other26.status;
  detail = other26.detail;
  unitName = other26.unitName;
  groups = other26.groups;
  __isset = other26.__isset;
}
LiveParamGroupListResponse& LiveParamGroupListResponse::operator=(const LiveParamGroupListResponse& other27) {
  status = other27.status;
  detail = other27.detail;
  unitName = other27.unitName;
  groups = other27.groups;
  __isset = other27.__isset;
  return *this;
}
void LiveParamGroupListResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamGroupListResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "unitName=" << to_string(unitName);
  out << ", " << "groups=" << to_string(groups);
  out << ")";
}


LiveParamSetRequest::~LiveParamSetRequest() noexcept {
}

LiveParamSetRequest::LiveParamSetRequest() noexcept
   : unitName(),
     grpName() {
}

void LiveParamSetRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void LiveParamSetRequest::__set_grpName(const std::string& val) {
  this->grpName = val;
}

void LiveParamSetRequest::__set_params(const std::map<std::string, std::string> & val) {
  this->params = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamSetRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamSetRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->grpName);
          this->__isset.grpName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->params.clear();
            uint32_t _size28;
            ::apache::thrift::protocol::TType _ktype29;
            ::apache::thrift::protocol::TType _vtype30;
            xfer += iprot->readMapBegin(_ktype29, _vtype30, _size28);
            uint32_t _i32;
            for (_i32 = 0; _i32 < _size28; ++_i32)
            {
              std::string _key33;
              xfer += iprot->readString(_key33);
              std::string& _val34 = this->params[_key33];
              xfer += iprot->readString(_val34);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.params = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamSetRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamSetRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("grpName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->grpName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("params", ::apache::thrift::protocol::T_MAP, 3);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->params.size()));
    std::map<std::string, std::string> ::const_iterator _iter35;
    for (_iter35 = this->params.begin(); _iter35 != this->params.end(); ++_iter35)
    {
      xfer += oprot->writeString(_iter35->first);
      xfer += oprot->writeString(_iter35->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamSetRequest &a, LiveParamSetRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.grpName, b.grpName);
  swap(a.params, b.params);
  swap(a.__isset, b.__isset);
}

bool LiveParamSetRequest::operator==(const LiveParamSetRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  if (!(grpName == rhs.grpName))
    return false;
  if (!(params == rhs.params))
    return false;
  return true;
}

LiveParamSetRequest::LiveParamSetRequest(const LiveParamSetRequest& other36) {
  unitName = other36.unitName;
  grpName = other36.grpName;
  params = other36.params;
  __isset = other36.__isset;
}
LiveParamSetRequest& LiveParamSetRequest::operator=(const LiveParamSetRequest& other37) {
  unitName = other37.unitName;
  grpName = other37.grpName;
  params = other37.params;
  __isset = other37.__isset;
  return *this;
}
void LiveParamSetRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamSetRequest(";
  out << "unitName=" << to_string(unitName);
  out << ", " << "grpName=" << to_string(grpName);
  out << ", " << "params=" << to_string(params);
  out << ")";
}


LiveParamSetResponse::~LiveParamSetResponse() noexcept {
}

LiveParamSetResponse::LiveParamSetResponse() noexcept
   : status(0),
     detail(),
     unitName() {
}

void LiveParamSetResponse::__set_status(const int32_t val) {
  this->status = val;
}

void LiveParamSetResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void LiveParamSetResponse::__set_unitName(const std::string& val) {
  this->unitName = val;
}
std::ostream& operator<<(std::ostream& out, const LiveParamSetResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LiveParamSetResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LiveParamSetResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LiveParamSetResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LiveParamSetResponse &a, LiveParamSetResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.unitName, b.unitName);
  swap(a.__isset, b.__isset);
}

bool LiveParamSetResponse::operator==(const LiveParamSetResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(unitName == rhs.unitName))
    return false;
  return true;
}

LiveParamSetResponse::LiveParamSetResponse(const LiveParamSetResponse& other38) {
  status = other38.status;
  detail = other38.detail;
  unitName = other38.unitName;
  __isset = other38.__isset;
}
LiveParamSetResponse& LiveParamSetResponse::operator=(const LiveParamSetResponse& other39) {
  status = other39.status;
  detail = other39.detail;
  unitName = other39.unitName;
  __isset = other39.__isset;
  return *this;
}
void LiveParamSetResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LiveParamSetResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "unitName=" << to_string(unitName);
  out << ")";
}


