/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef login_TYPES_H
#define login_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class LoginRequest;

class GroceryInfo;

class LoginResponse;

typedef struct _LoginRequest__isset {
  _LoginRequest__isset() : name(false), password(false) {}
  bool name :1;
  bool password :1;
} _LoginRequest__isset;

class LoginRequest : public virtual ::apache::thrift::TBase {
 public:

  LoginRequest(const LoginRequest&);
  LoginRequest& operator=(const LoginRequest&);
  LoginRequest() noexcept;

  virtual ~LoginRequest() noexcept;
  std::string name;
  std::string password;

  _LoginRequest__isset __isset;

  void __set_name(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const LoginRequest & rhs) const;
  bool operator != (const LoginRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LoginRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LoginRequest &a, LoginRequest &b);

std::ostream& operator<<(std::ostream& out, const LoginRequest& obj);

typedef struct _GroceryInfo__isset {
  _GroceryInfo__isset() : hostname(false), ip(false), port(false), token(false) {}
  bool hostname :1;
  bool ip :1;
  bool port :1;
  bool token :1;
} _GroceryInfo__isset;

class GroceryInfo : public virtual ::apache::thrift::TBase {
 public:

  GroceryInfo(const GroceryInfo&);
  GroceryInfo& operator=(const GroceryInfo&);
  GroceryInfo() noexcept;

  virtual ~GroceryInfo() noexcept;
  std::string hostname;
  std::string ip;
  int16_t port;
  std::string token;

  _GroceryInfo__isset __isset;

  void __set_hostname(const std::string& val);

  void __set_ip(const std::string& val);

  void __set_port(const int16_t val);

  void __set_token(const std::string& val);

  bool operator == (const GroceryInfo & rhs) const;
  bool operator != (const GroceryInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GroceryInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GroceryInfo &a, GroceryInfo &b);

std::ostream& operator<<(std::ostream& out, const GroceryInfo& obj);

typedef struct _LoginResponse__isset {
  _LoginResponse__isset() : status(false), detail(false), expireAt(false), groceries(false) {}
  bool status :1;
  bool detail :1;
  bool expireAt :1;
  bool groceries :1;
} _LoginResponse__isset;

class LoginResponse : public virtual ::apache::thrift::TBase {
 public:

  LoginResponse(const LoginResponse&);
  LoginResponse& operator=(const LoginResponse&);
  LoginResponse() noexcept;

  virtual ~LoginResponse() noexcept;
  int32_t status;
  std::string detail;
  int64_t expireAt;
  std::vector<GroceryInfo>  groceries;

  _LoginResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_expireAt(const int64_t val);

  void __set_groceries(const std::vector<GroceryInfo> & val);

  bool operator == (const LoginResponse & rhs) const;
  bool operator != (const LoginResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LoginResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LoginResponse &a, LoginResponse &b);

std::ostream& operator<<(std::ostream& out, const LoginResponse& obj);



#endif
