/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "login_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




LoginRequest::~LoginRequest() noexcept {
}

LoginRequest::LoginRequest() noexcept
   : name(),
     password() {
}

void LoginRequest::__set_name(const std::string& val) {
  this->name = val;
}

void LoginRequest::__set_password(const std::string& val) {
  this->password = val;
}
std::ostream& operator<<(std::ostream& out, const LoginRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LoginRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->password);
          this->__isset.password = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LoginRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LoginRequest");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("password", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->password);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LoginRequest &a, LoginRequest &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.password, b.password);
  swap(a.__isset, b.__isset);
}

bool LoginRequest::operator==(const LoginRequest & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(password == rhs.password))
    return false;
  return true;
}

LoginRequest::LoginRequest(const LoginRequest& other0) {
  name = other0.name;
  password = other0.password;
  __isset = other0.__isset;
}
LoginRequest& LoginRequest::operator=(const LoginRequest& other1) {
  name = other1.name;
  password = other1.password;
  __isset = other1.__isset;
  return *this;
}
void LoginRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LoginRequest(";
  out << "name=" << to_string(name);
  out << ", " << "password=" << to_string(password);
  out << ")";
}


GroceryInfo::~GroceryInfo() noexcept {
}

GroceryInfo::GroceryInfo() noexcept
   : hostname(),
     ip(),
     port(0),
     token() {
}

void GroceryInfo::__set_hostname(const std::string& val) {
  this->hostname = val;
}

void GroceryInfo::__set_ip(const std::string& val) {
  this->ip = val;
}

void GroceryInfo::__set_port(const int16_t val) {
  this->port = val;
}

void GroceryInfo::__set_token(const std::string& val) {
  this->token = val;
}
std::ostream& operator<<(std::ostream& out, const GroceryInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GroceryInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->hostname);
          this->__isset.hostname = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->ip);
          this->__isset.ip = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->token);
          this->__isset.token = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t GroceryInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GroceryInfo");

  xfer += oprot->writeFieldBegin("hostname", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->hostname);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("ip", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->ip);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I16, 3);
  xfer += oprot->writeI16(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("token", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->token);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GroceryInfo &a, GroceryInfo &b) {
  using ::std::swap;
  swap(a.hostname, b.hostname);
  swap(a.ip, b.ip);
  swap(a.port, b.port);
  swap(a.token, b.token);
  swap(a.__isset, b.__isset);
}

bool GroceryInfo::operator==(const GroceryInfo & rhs) const
{
  if (!(hostname == rhs.hostname))
    return false;
  if (!(ip == rhs.ip))
    return false;
  if (!(port == rhs.port))
    return false;
  if (!(token == rhs.token))
    return false;
  return true;
}

GroceryInfo::GroceryInfo(const GroceryInfo& other2) {
  hostname = other2.hostname;
  ip = other2.ip;
  port = other2.port;
  token = other2.token;
  __isset = other2.__isset;
}
GroceryInfo& GroceryInfo::operator=(const GroceryInfo& other3) {
  hostname = other3.hostname;
  ip = other3.ip;
  port = other3.port;
  token = other3.token;
  __isset = other3.__isset;
  return *this;
}
void GroceryInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GroceryInfo(";
  out << "hostname=" << to_string(hostname);
  out << ", " << "ip=" << to_string(ip);
  out << ", " << "port=" << to_string(port);
  out << ", " << "token=" << to_string(token);
  out << ")";
}


LoginResponse::~LoginResponse() noexcept {
}

LoginResponse::LoginResponse() noexcept
   : status(0),
     detail(),
     expireAt(0) {
}

void LoginResponse::__set_status(const int32_t val) {
  this->status = val;
}

void LoginResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void LoginResponse::__set_expireAt(const int64_t val) {
  this->expireAt = val;
}

void LoginResponse::__set_groceries(const std::vector<GroceryInfo> & val) {
  this->groceries = val;
}
std::ostream& operator<<(std::ostream& out, const LoginResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LoginResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->expireAt);
          this->__isset.expireAt = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->groceries.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->groceries.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->groceries[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.groceries = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LoginResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LoginResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("expireAt", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->expireAt);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("groceries", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->groceries.size()));
    std::vector<GroceryInfo> ::const_iterator _iter9;
    for (_iter9 = this->groceries.begin(); _iter9 != this->groceries.end(); ++_iter9)
    {
      xfer += (*_iter9).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LoginResponse &a, LoginResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.expireAt, b.expireAt);
  swap(a.groceries, b.groceries);
  swap(a.__isset, b.__isset);
}

bool LoginResponse::operator==(const LoginResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(expireAt == rhs.expireAt))
    return false;
  if (!(groceries == rhs.groceries))
    return false;
  return true;
}

LoginResponse::LoginResponse(const LoginResponse& other10) {
  status = other10.status;
  detail = other10.detail;
  expireAt = other10.expireAt;
  groceries = other10.groceries;
  __isset = other10.__isset;
}
LoginResponse& LoginResponse::operator=(const LoginResponse& other11) {
  status = other11.status;
  detail = other11.detail;
  expireAt = other11.expireAt;
  groceries = other11.groceries;
  __isset = other11.__isset;
  return *this;
}
void LoginResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LoginResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "expireAt=" << to_string(expireAt);
  out << ", " << "groceries=" << to_string(groceries);
  out << ")";
}


