/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "order_constants.h"



const orderConstants g_order_constants;

orderConstants::orderConstants() {
  WMESSAGE_ORDER_INSERT = 8193;

  WMESSAGE_ORDER_CANCEL = 8194;

  WMESSAGE_COMB_COMB = 8195;

  WMESSAGE_COMB_UNCOMB = 8196;

}



