/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "order_constants.h"



const orderConstants g_order_constants;

orderConstants::orderConstants() {
  WMESSAGE_ORDER_INSERT = 9216;

  WMESSAGE_ORDER_CANCEL = 9217;

  WMESSAGE_COMB_COMB = 9218;

  WMESSAGE_COMB_UNCOMB = 9219;

}



