/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef order_CONSTANTS_H
#define order_CONSTANTS_H

#include "order_types.h"



class orderConstants {
 public:
  orderConstants();

  int32_t WMESSAGE_ORDER_INSERT;
  int32_t WMESSAGE_ORDER_CANCEL;
  int32_t WMESSAGE_COMB_COMB;
  int32_t WMESSAGE_COMB_UNCOMB;
};

extern const orderConstants g_order_constants;



#endif
