/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "order_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




InsertOrderReq::~InsertOrderReq() noexcept {
}

InsertOrderReq::InsertOrderReq() noexcept
   : symbol(),
     account(),
     localId(),
     portfolio(),
     price(0),
     qty(0),
     isBuy(0),
     isOpen(0),
     isYesterday(0) {
}

void InsertOrderReq::__set_symbol(const std::string& val) {
  this->symbol = val;
}

void InsertOrderReq::__set_account(const std::string& val) {
  this->account = val;
}

void InsertOrderReq::__set_localId(const std::string& val) {
  this->localId = val;
}

void InsertOrderReq::__set_portfolio(const std::string& val) {
  this->portfolio = val;
}

void InsertOrderReq::__set_price(const double val) {
  this->price = val;
}

void InsertOrderReq::__set_qty(const int32_t val) {
  this->qty = val;
}

void InsertOrderReq::__set_isBuy(const bool val) {
  this->isBuy = val;
}

void InsertOrderReq::__set_isOpen(const bool val) {
  this->isOpen = val;
}

void InsertOrderReq::__set_isYesterday(const bool val) {
  this->isYesterday = val;
}
std::ostream& operator<<(std::ostream& out, const InsertOrderReq& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t InsertOrderReq::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->symbol);
          this->__isset.symbol = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->account);
          this->__isset.account = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->localId);
          this->__isset.localId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->portfolio);
          this->__isset.portfolio = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->price);
          this->__isset.price = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->qty);
          this->__isset.qty = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isBuy);
          this->__isset.isBuy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isOpen);
          this->__isset.isOpen = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isYesterday);
          this->__isset.isYesterday = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InsertOrderReq::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("InsertOrderReq");

  xfer += oprot->writeFieldBegin("symbol", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->symbol);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("account", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->account);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("localId", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->localId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("portfolio", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->portfolio);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("price", ::apache::thrift::protocol::T_DOUBLE, 5);
  xfer += oprot->writeDouble(this->price);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("qty", ::apache::thrift::protocol::T_I32, 6);
  xfer += oprot->writeI32(this->qty);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isBuy", ::apache::thrift::protocol::T_BOOL, 7);
  xfer += oprot->writeBool(this->isBuy);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isOpen", ::apache::thrift::protocol::T_BOOL, 8);
  xfer += oprot->writeBool(this->isOpen);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isYesterday", ::apache::thrift::protocol::T_BOOL, 9);
  xfer += oprot->writeBool(this->isYesterday);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(InsertOrderReq &a, InsertOrderReq &b) {
  using ::std::swap;
  swap(a.symbol, b.symbol);
  swap(a.account, b.account);
  swap(a.localId, b.localId);
  swap(a.portfolio, b.portfolio);
  swap(a.price, b.price);
  swap(a.qty, b.qty);
  swap(a.isBuy, b.isBuy);
  swap(a.isOpen, b.isOpen);
  swap(a.isYesterday, b.isYesterday);
  swap(a.__isset, b.__isset);
}

bool InsertOrderReq::operator==(const InsertOrderReq & rhs) const
{
  if (!(symbol == rhs.symbol))
    return false;
  if (!(account == rhs.account))
    return false;
  if (!(localId == rhs.localId))
    return false;
  if (!(portfolio == rhs.portfolio))
    return false;
  if (!(price == rhs.price))
    return false;
  if (!(qty == rhs.qty))
    return false;
  if (!(isBuy == rhs.isBuy))
    return false;
  if (!(isOpen == rhs.isOpen))
    return false;
  if (!(isYesterday == rhs.isYesterday))
    return false;
  return true;
}

InsertOrderReq::InsertOrderReq(const InsertOrderReq& other0) {
  symbol = other0.symbol;
  account = other0.account;
  localId = other0.localId;
  portfolio = other0.portfolio;
  price = other0.price;
  qty = other0.qty;
  isBuy = other0.isBuy;
  isOpen = other0.isOpen;
  isYesterday = other0.isYesterday;
  __isset = other0.__isset;
}
InsertOrderReq& InsertOrderReq::operator=(const InsertOrderReq& other1) {
  symbol = other1.symbol;
  account = other1.account;
  localId = other1.localId;
  portfolio = other1.portfolio;
  price = other1.price;
  qty = other1.qty;
  isBuy = other1.isBuy;
  isOpen = other1.isOpen;
  isYesterday = other1.isYesterday;
  __isset = other1.__isset;
  return *this;
}
void InsertOrderReq::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "InsertOrderReq(";
  out << "symbol=" << to_string(symbol);
  out << ", " << "account=" << to_string(account);
  out << ", " << "localId=" << to_string(localId);
  out << ", " << "portfolio=" << to_string(portfolio);
  out << ", " << "price=" << to_string(price);
  out << ", " << "qty=" << to_string(qty);
  out << ", " << "isBuy=" << to_string(isBuy);
  out << ", " << "isOpen=" << to_string(isOpen);
  out << ", " << "isYesterday=" << to_string(isYesterday);
  out << ")";
}


InsertOrderResponse::~InsertOrderResponse() noexcept {
}

InsertOrderResponse::InsertOrderResponse() noexcept
   : status(0),
     detail(),
     localId(),
     orderId(0) {
}

void InsertOrderResponse::__set_status(const int32_t val) {
  this->status = val;
}

void InsertOrderResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void InsertOrderResponse::__set_localId(const std::string& val) {
  this->localId = val;
}

void InsertOrderResponse::__set_orderId(const int32_t val) {
  this->orderId = val;
}
std::ostream& operator<<(std::ostream& out, const InsertOrderResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t InsertOrderResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->localId);
          this->__isset.localId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->orderId);
          this->__isset.orderId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InsertOrderResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("InsertOrderResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("localId", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->localId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("orderId", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(this->orderId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(InsertOrderResponse &a, InsertOrderResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.localId, b.localId);
  swap(a.orderId, b.orderId);
  swap(a.__isset, b.__isset);
}

bool InsertOrderResponse::operator==(const InsertOrderResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(localId == rhs.localId))
    return false;
  if (!(orderId == rhs.orderId))
    return false;
  return true;
}

InsertOrderResponse::InsertOrderResponse(const InsertOrderResponse& other2) {
  status = other2.status;
  detail = other2.detail;
  localId = other2.localId;
  orderId = other2.orderId;
  __isset = other2.__isset;
}
InsertOrderResponse& InsertOrderResponse::operator=(const InsertOrderResponse& other3) {
  status = other3.status;
  detail = other3.detail;
  localId = other3.localId;
  orderId = other3.orderId;
  __isset = other3.__isset;
  return *this;
}
void InsertOrderResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "InsertOrderResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "localId=" << to_string(localId);
  out << ", " << "orderId=" << to_string(orderId);
  out << ")";
}


CancelOrderReq::~CancelOrderReq() noexcept {
}

CancelOrderReq::CancelOrderReq() noexcept
   : orderId(0) {
}

void CancelOrderReq::__set_orderId(const int32_t val) {
  this->orderId = val;
}
std::ostream& operator<<(std::ostream& out, const CancelOrderReq& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CancelOrderReq::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->orderId);
          this->__isset.orderId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CancelOrderReq::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CancelOrderReq");

  xfer += oprot->writeFieldBegin("orderId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->orderId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CancelOrderReq &a, CancelOrderReq &b) {
  using ::std::swap;
  swap(a.orderId, b.orderId);
  swap(a.__isset, b.__isset);
}

bool CancelOrderReq::operator==(const CancelOrderReq & rhs) const
{
  if (!(orderId == rhs.orderId))
    return false;
  return true;
}

CancelOrderReq::CancelOrderReq(const CancelOrderReq& other4) noexcept {
  orderId = other4.orderId;
  __isset = other4.__isset;
}
CancelOrderReq& CancelOrderReq::operator=(const CancelOrderReq& other5) noexcept {
  orderId = other5.orderId;
  __isset = other5.__isset;
  return *this;
}
void CancelOrderReq::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CancelOrderReq(";
  out << "orderId=" << to_string(orderId);
  out << ")";
}


CancelOrderResponse::~CancelOrderResponse() noexcept {
}

CancelOrderResponse::CancelOrderResponse() noexcept
   : status(0),
     detail() {
}

void CancelOrderResponse::__set_status(const int32_t val) {
  this->status = val;
}

void CancelOrderResponse::__set_detail(const std::string& val) {
  this->detail = val;
}
std::ostream& operator<<(std::ostream& out, const CancelOrderResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CancelOrderResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CancelOrderResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CancelOrderResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CancelOrderResponse &a, CancelOrderResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.__isset, b.__isset);
}

bool CancelOrderResponse::operator==(const CancelOrderResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  return true;
}

CancelOrderResponse::CancelOrderResponse(const CancelOrderResponse& other6) {
  status = other6.status;
  detail = other6.detail;
  __isset = other6.__isset;
}
CancelOrderResponse& CancelOrderResponse::operator=(const CancelOrderResponse& other7) {
  status = other7.status;
  detail = other7.detail;
  __isset = other7.__isset;
  return *this;
}
void CancelOrderResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CancelOrderResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ")";
}


SendCombRequest::~SendCombRequest() noexcept {
}

SendCombRequest::SendCombRequest() noexcept
   : combStrategy(),
     localCombId(),
     symbol1(),
     isBuy1(0),
     symbol2(),
     isBuy2(0),
     qty(0) {
}

void SendCombRequest::__set_combStrategy(const std::string& val) {
  this->combStrategy = val;
}

void SendCombRequest::__set_localCombId(const std::string& val) {
  this->localCombId = val;
}

void SendCombRequest::__set_symbol1(const std::string& val) {
  this->symbol1 = val;
}

void SendCombRequest::__set_isBuy1(const bool val) {
  this->isBuy1 = val;
}

void SendCombRequest::__set_symbol2(const std::string& val) {
  this->symbol2 = val;
}

void SendCombRequest::__set_isBuy2(const bool val) {
  this->isBuy2 = val;
}

void SendCombRequest::__set_qty(const int32_t val) {
  this->qty = val;
}
std::ostream& operator<<(std::ostream& out, const SendCombRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SendCombRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->combStrategy);
          this->__isset.combStrategy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->localCombId);
          this->__isset.localCombId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->symbol1);
          this->__isset.symbol1 = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isBuy1);
          this->__isset.isBuy1 = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->symbol2);
          this->__isset.symbol2 = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->isBuy2);
          this->__isset.isBuy2 = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->qty);
          this->__isset.qty = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SendCombRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SendCombRequest");

  xfer += oprot->writeFieldBegin("combStrategy", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->combStrategy);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("localCombId", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->localCombId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("symbol1", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->symbol1);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isBuy1", ::apache::thrift::protocol::T_BOOL, 4);
  xfer += oprot->writeBool(this->isBuy1);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("symbol2", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->symbol2);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("isBuy2", ::apache::thrift::protocol::T_BOOL, 6);
  xfer += oprot->writeBool(this->isBuy2);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("qty", ::apache::thrift::protocol::T_I32, 7);
  xfer += oprot->writeI32(this->qty);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SendCombRequest &a, SendCombRequest &b) {
  using ::std::swap;
  swap(a.combStrategy, b.combStrategy);
  swap(a.localCombId, b.localCombId);
  swap(a.symbol1, b.symbol1);
  swap(a.isBuy1, b.isBuy1);
  swap(a.symbol2, b.symbol2);
  swap(a.isBuy2, b.isBuy2);
  swap(a.qty, b.qty);
  swap(a.__isset, b.__isset);
}

bool SendCombRequest::operator==(const SendCombRequest & rhs) const
{
  if (!(combStrategy == rhs.combStrategy))
    return false;
  if (!(localCombId == rhs.localCombId))
    return false;
  if (!(symbol1 == rhs.symbol1))
    return false;
  if (!(isBuy1 == rhs.isBuy1))
    return false;
  if (!(symbol2 == rhs.symbol2))
    return false;
  if (!(isBuy2 == rhs.isBuy2))
    return false;
  if (!(qty == rhs.qty))
    return false;
  return true;
}

SendCombRequest::SendCombRequest(const SendCombRequest& other8) {
  combStrategy = other8.combStrategy;
  localCombId = other8.localCombId;
  symbol1 = other8.symbol1;
  isBuy1 = other8.isBuy1;
  symbol2 = other8.symbol2;
  isBuy2 = other8.isBuy2;
  qty = other8.qty;
  __isset = other8.__isset;
}
SendCombRequest& SendCombRequest::operator=(const SendCombRequest& other9) {
  combStrategy = other9.combStrategy;
  localCombId = other9.localCombId;
  symbol1 = other9.symbol1;
  isBuy1 = other9.isBuy1;
  symbol2 = other9.symbol2;
  isBuy2 = other9.isBuy2;
  qty = other9.qty;
  __isset = other9.__isset;
  return *this;
}
void SendCombRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SendCombRequest(";
  out << "combStrategy=" << to_string(combStrategy);
  out << ", " << "localCombId=" << to_string(localCombId);
  out << ", " << "symbol1=" << to_string(symbol1);
  out << ", " << "isBuy1=" << to_string(isBuy1);
  out << ", " << "symbol2=" << to_string(symbol2);
  out << ", " << "isBuy2=" << to_string(isBuy2);
  out << ", " << "qty=" << to_string(qty);
  out << ")";
}


SendCombResponse::~SendCombResponse() noexcept {
}

SendCombResponse::SendCombResponse() noexcept
   : status(0),
     detail(),
     localCombId(),
     combId(0) {
}

void SendCombResponse::__set_status(const int32_t val) {
  this->status = val;
}

void SendCombResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void SendCombResponse::__set_localCombId(const std::string& val) {
  this->localCombId = val;
}

void SendCombResponse::__set_combId(const int32_t val) {
  this->combId = val;
}
std::ostream& operator<<(std::ostream& out, const SendCombResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SendCombResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->localCombId);
          this->__isset.localCombId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->combId);
          this->__isset.combId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SendCombResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SendCombResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("localCombId", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->localCombId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("combId", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(this->combId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SendCombResponse &a, SendCombResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.localCombId, b.localCombId);
  swap(a.combId, b.combId);
  swap(a.__isset, b.__isset);
}

bool SendCombResponse::operator==(const SendCombResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(localCombId == rhs.localCombId))
    return false;
  if (!(combId == rhs.combId))
    return false;
  return true;
}

SendCombResponse::SendCombResponse(const SendCombResponse& other10) {
  status = other10.status;
  detail = other10.detail;
  localCombId = other10.localCombId;
  combId = other10.combId;
  __isset = other10.__isset;
}
SendCombResponse& SendCombResponse::operator=(const SendCombResponse& other11) {
  status = other11.status;
  detail = other11.detail;
  localCombId = other11.localCombId;
  combId = other11.combId;
  __isset = other11.__isset;
  return *this;
}
void SendCombResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SendCombResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "localCombId=" << to_string(localCombId);
  out << ", " << "combId=" << to_string(combId);
  out << ")";
}


SendUncombRequest::~SendUncombRequest() noexcept {
}

SendUncombRequest::SendUncombRequest() noexcept
   : combId(0),
     systemCombId() {
}

void SendUncombRequest::__set_combId(const int32_t val) {
  this->combId = val;
}

void SendUncombRequest::__set_systemCombId(const std::string& val) {
  this->systemCombId = val;
}
std::ostream& operator<<(std::ostream& out, const SendUncombRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SendUncombRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->combId);
          this->__isset.combId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->systemCombId);
          this->__isset.systemCombId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SendUncombRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SendUncombRequest");

  xfer += oprot->writeFieldBegin("combId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->combId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("systemCombId", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->systemCombId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SendUncombRequest &a, SendUncombRequest &b) {
  using ::std::swap;
  swap(a.combId, b.combId);
  swap(a.systemCombId, b.systemCombId);
  swap(a.__isset, b.__isset);
}

bool SendUncombRequest::operator==(const SendUncombRequest & rhs) const
{
  if (!(combId == rhs.combId))
    return false;
  if (!(systemCombId == rhs.systemCombId))
    return false;
  return true;
}

SendUncombRequest::SendUncombRequest(const SendUncombRequest& other12) {
  combId = other12.combId;
  systemCombId = other12.systemCombId;
  __isset = other12.__isset;
}
SendUncombRequest& SendUncombRequest::operator=(const SendUncombRequest& other13) {
  combId = other13.combId;
  systemCombId = other13.systemCombId;
  __isset = other13.__isset;
  return *this;
}
void SendUncombRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SendUncombRequest(";
  out << "combId=" << to_string(combId);
  out << ", " << "systemCombId=" << to_string(systemCombId);
  out << ")";
}


SendUncombResponse::~SendUncombResponse() noexcept {
}

SendUncombResponse::SendUncombResponse() noexcept
   : status(0),
     detail() {
}

void SendUncombResponse::__set_status(const int32_t val) {
  this->status = val;
}

void SendUncombResponse::__set_detail(const std::string& val) {
  this->detail = val;
}
std::ostream& operator<<(std::ostream& out, const SendUncombResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SendUncombResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SendUncombResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SendUncombResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SendUncombResponse &a, SendUncombResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.__isset, b.__isset);
}

bool SendUncombResponse::operator==(const SendUncombResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  return true;
}

SendUncombResponse::SendUncombResponse(const SendUncombResponse& other14) {
  status = other14.status;
  detail = other14.detail;
  __isset = other14.__isset;
}
SendUncombResponse& SendUncombResponse::operator=(const SendUncombResponse& other15) {
  status = other15.status;
  detail = other15.detail;
  __isset = other15.__isset;
  return *this;
}
void SendUncombResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SendUncombResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ")";
}


