/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef order_TYPES_H
#define order_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class InsertOrderRequest;

class InsertOrderResponse;

class CancelOrderRequest;

class CancelOrderResponse;

class SendCombRequest;

class SendCombResponse;

class SendUncombRequest;

class SendUncombResponse;

typedef struct _InsertOrderRequest__isset {
  _InsertOrderRequest__isset() : symbol(false), account(false), localId(false), portfolio(false), orderType(false), price(false), qty(false), isBuy(false), isOpen(false), isYesterday(false) {}
  bool symbol :1;
  bool account :1;
  bool localId :1;
  bool portfolio :1;
  bool orderType :1;
  bool price :1;
  bool qty :1;
  bool isBuy :1;
  bool isOpen :1;
  bool isYesterday :1;
} _InsertOrderRequest__isset;

class InsertOrderRequest : public virtual ::apache::thrift::TBase {
 public:

  InsertOrderRequest(const InsertOrderRequest&);
  InsertOrderRequest& operator=(const InsertOrderRequest&);
  InsertOrderRequest() noexcept;

  virtual ~InsertOrderRequest() noexcept;
  std::string symbol;
  std::string account;
  std::string localId;
  std::string portfolio;
  std::string orderType;
  double price;
  int32_t qty;
  bool isBuy;
  bool isOpen;
  bool isYesterday;

  _InsertOrderRequest__isset __isset;

  void __set_symbol(const std::string& val);

  void __set_account(const std::string& val);

  void __set_localId(const std::string& val);

  void __set_portfolio(const std::string& val);

  void __set_orderType(const std::string& val);

  void __set_price(const double val);

  void __set_qty(const int32_t val);

  void __set_isBuy(const bool val);

  void __set_isOpen(const bool val);

  void __set_isYesterday(const bool val);

  bool operator == (const InsertOrderRequest & rhs) const;
  bool operator != (const InsertOrderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InsertOrderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InsertOrderRequest &a, InsertOrderRequest &b);

std::ostream& operator<<(std::ostream& out, const InsertOrderRequest& obj);

typedef struct _InsertOrderResponse__isset {
  _InsertOrderResponse__isset() : status(false), detail(false), localId(false), orderId(false) {}
  bool status :1;
  bool detail :1;
  bool localId :1;
  bool orderId :1;
} _InsertOrderResponse__isset;

class InsertOrderResponse : public virtual ::apache::thrift::TBase {
 public:

  InsertOrderResponse(const InsertOrderResponse&);
  InsertOrderResponse& operator=(const InsertOrderResponse&);
  InsertOrderResponse() noexcept;

  virtual ~InsertOrderResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string localId;
  int32_t orderId;

  _InsertOrderResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_localId(const std::string& val);

  void __set_orderId(const int32_t val);

  bool operator == (const InsertOrderResponse & rhs) const;
  bool operator != (const InsertOrderResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InsertOrderResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InsertOrderResponse &a, InsertOrderResponse &b);

std::ostream& operator<<(std::ostream& out, const InsertOrderResponse& obj);

typedef struct _CancelOrderRequest__isset {
  _CancelOrderRequest__isset() : orderId(false) {}
  bool orderId :1;
} _CancelOrderRequest__isset;

class CancelOrderRequest : public virtual ::apache::thrift::TBase {
 public:

  CancelOrderRequest(const CancelOrderRequest&) noexcept;
  CancelOrderRequest& operator=(const CancelOrderRequest&) noexcept;
  CancelOrderRequest() noexcept;

  virtual ~CancelOrderRequest() noexcept;
  int32_t orderId;

  _CancelOrderRequest__isset __isset;

  void __set_orderId(const int32_t val);

  bool operator == (const CancelOrderRequest & rhs) const;
  bool operator != (const CancelOrderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CancelOrderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CancelOrderRequest &a, CancelOrderRequest &b);

std::ostream& operator<<(std::ostream& out, const CancelOrderRequest& obj);

typedef struct _CancelOrderResponse__isset {
  _CancelOrderResponse__isset() : status(false), detail(false) {}
  bool status :1;
  bool detail :1;
} _CancelOrderResponse__isset;

class CancelOrderResponse : public virtual ::apache::thrift::TBase {
 public:

  CancelOrderResponse(const CancelOrderResponse&);
  CancelOrderResponse& operator=(const CancelOrderResponse&);
  CancelOrderResponse() noexcept;

  virtual ~CancelOrderResponse() noexcept;
  int32_t status;
  std::string detail;

  _CancelOrderResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  bool operator == (const CancelOrderResponse & rhs) const;
  bool operator != (const CancelOrderResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CancelOrderResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CancelOrderResponse &a, CancelOrderResponse &b);

std::ostream& operator<<(std::ostream& out, const CancelOrderResponse& obj);

typedef struct _SendCombRequest__isset {
  _SendCombRequest__isset() : combStrategy(false), localCombId(false), symbol1(false), isBuy1(false), symbol2(false), isBuy2(false), qty(false) {}
  bool combStrategy :1;
  bool localCombId :1;
  bool symbol1 :1;
  bool isBuy1 :1;
  bool symbol2 :1;
  bool isBuy2 :1;
  bool qty :1;
} _SendCombRequest__isset;

class SendCombRequest : public virtual ::apache::thrift::TBase {
 public:

  SendCombRequest(const SendCombRequest&);
  SendCombRequest& operator=(const SendCombRequest&);
  SendCombRequest() noexcept;

  virtual ~SendCombRequest() noexcept;
  std::string combStrategy;
  std::string localCombId;
  std::string symbol1;
  bool isBuy1;
  std::string symbol2;
  bool isBuy2;
  int32_t qty;

  _SendCombRequest__isset __isset;

  void __set_combStrategy(const std::string& val);

  void __set_localCombId(const std::string& val);

  void __set_symbol1(const std::string& val);

  void __set_isBuy1(const bool val);

  void __set_symbol2(const std::string& val);

  void __set_isBuy2(const bool val);

  void __set_qty(const int32_t val);

  bool operator == (const SendCombRequest & rhs) const;
  bool operator != (const SendCombRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SendCombRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SendCombRequest &a, SendCombRequest &b);

std::ostream& operator<<(std::ostream& out, const SendCombRequest& obj);

typedef struct _SendCombResponse__isset {
  _SendCombResponse__isset() : status(false), detail(false), localCombId(false), combId(false) {}
  bool status :1;
  bool detail :1;
  bool localCombId :1;
  bool combId :1;
} _SendCombResponse__isset;

class SendCombResponse : public virtual ::apache::thrift::TBase {
 public:

  SendCombResponse(const SendCombResponse&);
  SendCombResponse& operator=(const SendCombResponse&);
  SendCombResponse() noexcept;

  virtual ~SendCombResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string localCombId;
  int32_t combId;

  _SendCombResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_localCombId(const std::string& val);

  void __set_combId(const int32_t val);

  bool operator == (const SendCombResponse & rhs) const;
  bool operator != (const SendCombResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SendCombResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SendCombResponse &a, SendCombResponse &b);

std::ostream& operator<<(std::ostream& out, const SendCombResponse& obj);

typedef struct _SendUncombRequest__isset {
  _SendUncombRequest__isset() : combId(false), systemCombId(false) {}
  bool combId :1;
  bool systemCombId :1;
} _SendUncombRequest__isset;

class SendUncombRequest : public virtual ::apache::thrift::TBase {
 public:

  SendUncombRequest(const SendUncombRequest&);
  SendUncombRequest& operator=(const SendUncombRequest&);
  SendUncombRequest() noexcept;

  virtual ~SendUncombRequest() noexcept;
  int32_t combId;
  std::string systemCombId;

  _SendUncombRequest__isset __isset;

  void __set_combId(const int32_t val);

  void __set_systemCombId(const std::string& val);

  bool operator == (const SendUncombRequest & rhs) const;
  bool operator != (const SendUncombRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SendUncombRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SendUncombRequest &a, SendUncombRequest &b);

std::ostream& operator<<(std::ostream& out, const SendUncombRequest& obj);

typedef struct _SendUncombResponse__isset {
  _SendUncombResponse__isset() : status(false), detail(false) {}
  bool status :1;
  bool detail :1;
} _SendUncombResponse__isset;

class SendUncombResponse : public virtual ::apache::thrift::TBase {
 public:

  SendUncombResponse(const SendUncombResponse&);
  SendUncombResponse& operator=(const SendUncombResponse&);
  SendUncombResponse() noexcept;

  virtual ~SendUncombResponse() noexcept;
  int32_t status;
  std::string detail;

  _SendUncombResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  bool operator == (const SendUncombResponse & rhs) const;
  bool operator != (const SendUncombResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SendUncombResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SendUncombResponse &a, SendUncombResponse &b);

std::ostream& operator<<(std::ostream& out, const SendUncombResponse& obj);



#endif
