/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "strategy_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _kStrategyTradingModeValues[] = {
  StrategyTradingMode::UNKNOWN,
  StrategyTradingMode::TAKING,
  StrategyTradingMode::MAKING,
  StrategyTradingMode::TRADING
};
const char* _kStrategyTradingModeNames[] = {
  "UNKNOWN",
  "TAKING",
  "MAKING",
  "TRADING"
};
const std::map<int, const char*> _StrategyTradingMode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kStrategyTradingModeValues, _kStrategyTradingModeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const StrategyTradingMode::type& val) {
  std::map<int, const char*>::const_iterator it = _StrategyTradingMode_VALUES_TO_NAMES.find(val);
  if (it != _StrategyTradingMode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const StrategyTradingMode::type& val) {
  std::map<int, const char*>::const_iterator it = _StrategyTradingMode_VALUES_TO_NAMES.find(val);
  if (it != _StrategyTradingMode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ListStrategyRequest::~ListStrategyRequest() noexcept {
}

ListStrategyRequest::ListStrategyRequest() noexcept
   : unitName() {
}

void ListStrategyRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}
std::ostream& operator<<(std::ostream& out, const ListStrategyRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListStrategyRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListStrategyRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListStrategyRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListStrategyRequest &a, ListStrategyRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.__isset, b.__isset);
}

bool ListStrategyRequest::operator==(const ListStrategyRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  return true;
}

ListStrategyRequest::ListStrategyRequest(const ListStrategyRequest& other0) {
  unitName = other0.unitName;
  __isset = other0.__isset;
}
ListStrategyRequest& ListStrategyRequest::operator=(const ListStrategyRequest& other1) {
  unitName = other1.unitName;
  __isset = other1.__isset;
  return *this;
}
void ListStrategyRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListStrategyRequest(";
  out << "unitName=" << to_string(unitName);
  out << ")";
}


LegInfo::~LegInfo() noexcept {
}

LegInfo::LegInfo() noexcept
   : name(),
     leg(0),
     future(),
     optionChain(),
     countFuture(0) {
}

void LegInfo::__set_name(const std::string& val) {
  this->name = val;
}

void LegInfo::__set_leg(const int32_t val) {
  this->leg = val;
}

void LegInfo::__set_future(const std::string& val) {
  this->future = val;
}

void LegInfo::__set_optionChain(const std::string& val) {
  this->optionChain = val;
}

void LegInfo::__set_countFuture(const bool val) {
  this->countFuture = val;
}
std::ostream& operator<<(std::ostream& out, const LegInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LegInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->leg);
          this->__isset.leg = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->future);
          this->__isset.future = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->optionChain);
          this->__isset.optionChain = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->countFuture);
          this->__isset.countFuture = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LegInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LegInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("leg", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->leg);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("future", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->future);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("optionChain", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->optionChain);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("countFuture", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->countFuture);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LegInfo &a, LegInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.leg, b.leg);
  swap(a.future, b.future);
  swap(a.optionChain, b.optionChain);
  swap(a.countFuture, b.countFuture);
  swap(a.__isset, b.__isset);
}

bool LegInfo::operator==(const LegInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(leg == rhs.leg))
    return false;
  if (!(future == rhs.future))
    return false;
  if (!(optionChain == rhs.optionChain))
    return false;
  if (!(countFuture == rhs.countFuture))
    return false;
  return true;
}

LegInfo::LegInfo(const LegInfo& other2) {
  name = other2.name;
  leg = other2.leg;
  future = other2.future;
  optionChain = other2.optionChain;
  countFuture = other2.countFuture;
  __isset = other2.__isset;
}
LegInfo& LegInfo::operator=(const LegInfo& other3) {
  name = other3.name;
  leg = other3.leg;
  future = other3.future;
  optionChain = other3.optionChain;
  countFuture = other3.countFuture;
  __isset = other3.__isset;
  return *this;
}
void LegInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LegInfo(";
  out << "name=" << to_string(name);
  out << ", " << "leg=" << to_string(leg);
  out << ", " << "future=" << to_string(future);
  out << ", " << "optionChain=" << to_string(optionChain);
  out << ", " << "countFuture=" << to_string(countFuture);
  out << ")";
}


RiskInfo::~RiskInfo() noexcept {
}

RiskInfo::RiskInfo() noexcept
   : name(),
     shortcut(),
     lpgName() {
}

void RiskInfo::__set_name(const std::string& val) {
  this->name = val;
}

void RiskInfo::__set_shortcut(const std::string& val) {
  this->shortcut = val;
}

void RiskInfo::__set_lpgName(const std::string& val) {
  this->lpgName = val;
}
std::ostream& operator<<(std::ostream& out, const RiskInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RiskInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->shortcut);
          this->__isset.shortcut = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->lpgName);
          this->__isset.lpgName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RiskInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RiskInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("shortcut", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->shortcut);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("lpgName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->lpgName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RiskInfo &a, RiskInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.shortcut, b.shortcut);
  swap(a.lpgName, b.lpgName);
  swap(a.__isset, b.__isset);
}

bool RiskInfo::operator==(const RiskInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(shortcut == rhs.shortcut))
    return false;
  if (!(lpgName == rhs.lpgName))
    return false;
  return true;
}

RiskInfo::RiskInfo(const RiskInfo& other4) {
  name = other4.name;
  shortcut = other4.shortcut;
  lpgName = other4.lpgName;
  __isset = other4.__isset;
}
RiskInfo& RiskInfo::operator=(const RiskInfo& other5) {
  name = other5.name;
  shortcut = other5.shortcut;
  lpgName = other5.lpgName;
  __isset = other5.__isset;
  return *this;
}
void RiskInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RiskInfo(";
  out << "name=" << to_string(name);
  out << ", " << "shortcut=" << to_string(shortcut);
  out << ", " << "lpgName=" << to_string(lpgName);
  out << ")";
}


AlphaInfo::~AlphaInfo() noexcept {
}

AlphaInfo::AlphaInfo() noexcept
   : id(0),
     name(),
     lpgName() {
}

void AlphaInfo::__set_id(const int32_t val) {
  this->id = val;
}

void AlphaInfo::__set_name(const std::string& val) {
  this->name = val;
}

void AlphaInfo::__set_lpgName(const std::string& val) {
  this->lpgName = val;
}
std::ostream& operator<<(std::ostream& out, const AlphaInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AlphaInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->lpgName);
          this->__isset.lpgName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AlphaInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AlphaInfo");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("lpgName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->lpgName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AlphaInfo &a, AlphaInfo &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.name, b.name);
  swap(a.lpgName, b.lpgName);
  swap(a.__isset, b.__isset);
}

bool AlphaInfo::operator==(const AlphaInfo & rhs) const
{
  if (!(id == rhs.id))
    return false;
  if (!(name == rhs.name))
    return false;
  if (!(lpgName == rhs.lpgName))
    return false;
  return true;
}

AlphaInfo::AlphaInfo(const AlphaInfo& other6) {
  id = other6.id;
  name = other6.name;
  lpgName = other6.lpgName;
  __isset = other6.__isset;
}
AlphaInfo& AlphaInfo::operator=(const AlphaInfo& other7) {
  id = other7.id;
  name = other7.name;
  lpgName = other7.lpgName;
  __isset = other7.__isset;
  return *this;
}
void AlphaInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AlphaInfo(";
  out << "id=" << to_string(id);
  out << ", " << "name=" << to_string(name);
  out << ", " << "lpgName=" << to_string(lpgName);
  out << ")";
}


StrategyInfo::~StrategyInfo() noexcept {
}

StrategyInfo::StrategyInfo() noexcept
   : name() {
}

void StrategyInfo::__set_name(const std::string& val) {
  this->name = val;
}

void StrategyInfo::__set_attributes(const std::map<std::string, std::string> & val) {
  this->attributes = val;
}

void StrategyInfo::__set_legs(const std::vector<LegInfo> & val) {
  this->legs = val;
}

void StrategyInfo::__set_risks(const std::vector<RiskInfo> & val) {
  this->risks = val;
}

void StrategyInfo::__set_alphas(const std::vector<AlphaInfo> & val) {
  this->alphas = val;
}

void StrategyInfo::__set_topics(const std::map<std::string, int32_t> & val) {
  this->topics = val;
}

void StrategyInfo::__set_extraLpgs(const std::vector<std::string> & val) {
  this->extraLpgs = val;
}
std::ostream& operator<<(std::ostream& out, const StrategyInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StrategyInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->attributes.clear();
            uint32_t _size8;
            ::apache::thrift::protocol::TType _ktype9;
            ::apache::thrift::protocol::TType _vtype10;
            xfer += iprot->readMapBegin(_ktype9, _vtype10, _size8);
            uint32_t _i12;
            for (_i12 = 0; _i12 < _size8; ++_i12)
            {
              std::string _key13;
              xfer += iprot->readString(_key13);
              std::string& _val14 = this->attributes[_key13];
              xfer += iprot->readString(_val14);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.attributes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->legs.clear();
            uint32_t _size15;
            ::apache::thrift::protocol::TType _etype18;
            xfer += iprot->readListBegin(_etype18, _size15);
            this->legs.resize(_size15);
            uint32_t _i19;
            for (_i19 = 0; _i19 < _size15; ++_i19)
            {
              xfer += this->legs[_i19].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.legs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->risks.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readListBegin(_etype23, _size20);
            this->risks.resize(_size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              xfer += this->risks[_i24].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.risks = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->alphas.clear();
            uint32_t _size25;
            ::apache::thrift::protocol::TType _etype28;
            xfer += iprot->readListBegin(_etype28, _size25);
            this->alphas.resize(_size25);
            uint32_t _i29;
            for (_i29 = 0; _i29 < _size25; ++_i29)
            {
              xfer += this->alphas[_i29].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.alphas = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->topics.clear();
            uint32_t _size30;
            ::apache::thrift::protocol::TType _ktype31;
            ::apache::thrift::protocol::TType _vtype32;
            xfer += iprot->readMapBegin(_ktype31, _vtype32, _size30);
            uint32_t _i34;
            for (_i34 = 0; _i34 < _size30; ++_i34)
            {
              std::string _key35;
              xfer += iprot->readString(_key35);
              int32_t& _val36 = this->topics[_key35];
              xfer += iprot->readI32(_val36);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.topics = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->extraLpgs.clear();
            uint32_t _size37;
            ::apache::thrift::protocol::TType _etype40;
            xfer += iprot->readListBegin(_etype40, _size37);
            this->extraLpgs.resize(_size37);
            uint32_t _i41;
            for (_i41 = 0; _i41 < _size37; ++_i41)
            {
              xfer += iprot->readString(this->extraLpgs[_i41]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.extraLpgs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StrategyInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StrategyInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("attributes", ::apache::thrift::protocol::T_MAP, 2);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->attributes.size()));
    std::map<std::string, std::string> ::const_iterator _iter42;
    for (_iter42 = this->attributes.begin(); _iter42 != this->attributes.end(); ++_iter42)
    {
      xfer += oprot->writeString(_iter42->first);
      xfer += oprot->writeString(_iter42->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("legs", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->legs.size()));
    std::vector<LegInfo> ::const_iterator _iter43;
    for (_iter43 = this->legs.begin(); _iter43 != this->legs.end(); ++_iter43)
    {
      xfer += (*_iter43).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("risks", ::apache::thrift::protocol::T_LIST, 6);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->risks.size()));
    std::vector<RiskInfo> ::const_iterator _iter44;
    for (_iter44 = this->risks.begin(); _iter44 != this->risks.end(); ++_iter44)
    {
      xfer += (*_iter44).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("alphas", ::apache::thrift::protocol::T_LIST, 7);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->alphas.size()));
    std::vector<AlphaInfo> ::const_iterator _iter45;
    for (_iter45 = this->alphas.begin(); _iter45 != this->alphas.end(); ++_iter45)
    {
      xfer += (*_iter45).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("topics", ::apache::thrift::protocol::T_MAP, 8);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->topics.size()));
    std::map<std::string, int32_t> ::const_iterator _iter46;
    for (_iter46 = this->topics.begin(); _iter46 != this->topics.end(); ++_iter46)
    {
      xfer += oprot->writeString(_iter46->first);
      xfer += oprot->writeI32(_iter46->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("extraLpgs", ::apache::thrift::protocol::T_LIST, 9);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->extraLpgs.size()));
    std::vector<std::string> ::const_iterator _iter47;
    for (_iter47 = this->extraLpgs.begin(); _iter47 != this->extraLpgs.end(); ++_iter47)
    {
      xfer += oprot->writeString((*_iter47));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StrategyInfo &a, StrategyInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.attributes, b.attributes);
  swap(a.legs, b.legs);
  swap(a.risks, b.risks);
  swap(a.alphas, b.alphas);
  swap(a.topics, b.topics);
  swap(a.extraLpgs, b.extraLpgs);
  swap(a.__isset, b.__isset);
}

bool StrategyInfo::operator==(const StrategyInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(attributes == rhs.attributes))
    return false;
  if (!(legs == rhs.legs))
    return false;
  if (!(risks == rhs.risks))
    return false;
  if (!(alphas == rhs.alphas))
    return false;
  if (!(topics == rhs.topics))
    return false;
  if (!(extraLpgs == rhs.extraLpgs))
    return false;
  return true;
}

StrategyInfo::StrategyInfo(const StrategyInfo& other48) {
  name = other48.name;
  attributes = other48.attributes;
  legs = other48.legs;
  risks = other48.risks;
  alphas = other48.alphas;
  topics = other48.topics;
  extraLpgs = other48.extraLpgs;
  __isset = other48.__isset;
}
StrategyInfo& StrategyInfo::operator=(const StrategyInfo& other49) {
  name = other49.name;
  attributes = other49.attributes;
  legs = other49.legs;
  risks = other49.risks;
  alphas = other49.alphas;
  topics = other49.topics;
  extraLpgs = other49.extraLpgs;
  __isset = other49.__isset;
  return *this;
}
void StrategyInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StrategyInfo(";
  out << "name=" << to_string(name);
  out << ", " << "attributes=" << to_string(attributes);
  out << ", " << "legs=" << to_string(legs);
  out << ", " << "risks=" << to_string(risks);
  out << ", " << "alphas=" << to_string(alphas);
  out << ", " << "topics=" << to_string(topics);
  out << ", " << "extraLpgs=" << to_string(extraLpgs);
  out << ")";
}


ListStrategyResponse::~ListStrategyResponse() noexcept {
}

ListStrategyResponse::ListStrategyResponse() noexcept
   : status(0),
     detail(),
     unitName() {
}

void ListStrategyResponse::__set_status(const int32_t val) {
  this->status = val;
}

void ListStrategyResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void ListStrategyResponse::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void ListStrategyResponse::__set_strategies(const std::vector<StrategyInfo> & val) {
  this->strategies = val;
}

void ListStrategyResponse::__set_accounts(const std::vector<std::string> & val) {
  this->accounts = val;
}
std::ostream& operator<<(std::ostream& out, const ListStrategyResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListStrategyResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->strategies.clear();
            uint32_t _size50;
            ::apache::thrift::protocol::TType _etype53;
            xfer += iprot->readListBegin(_etype53, _size50);
            this->strategies.resize(_size50);
            uint32_t _i54;
            for (_i54 = 0; _i54 < _size50; ++_i54)
            {
              xfer += this->strategies[_i54].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.strategies = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->accounts.clear();
            uint32_t _size55;
            ::apache::thrift::protocol::TType _etype58;
            xfer += iprot->readListBegin(_etype58, _size55);
            this->accounts.resize(_size55);
            uint32_t _i59;
            for (_i59 = 0; _i59 < _size55; ++_i59)
            {
              xfer += iprot->readString(this->accounts[_i59]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.accounts = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListStrategyResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListStrategyResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("strategies", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->strategies.size()));
    std::vector<StrategyInfo> ::const_iterator _iter60;
    for (_iter60 = this->strategies.begin(); _iter60 != this->strategies.end(); ++_iter60)
    {
      xfer += (*_iter60).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("accounts", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->accounts.size()));
    std::vector<std::string> ::const_iterator _iter61;
    for (_iter61 = this->accounts.begin(); _iter61 != this->accounts.end(); ++_iter61)
    {
      xfer += oprot->writeString((*_iter61));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListStrategyResponse &a, ListStrategyResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.unitName, b.unitName);
  swap(a.strategies, b.strategies);
  swap(a.accounts, b.accounts);
  swap(a.__isset, b.__isset);
}

bool ListStrategyResponse::operator==(const ListStrategyResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(unitName == rhs.unitName))
    return false;
  if (!(strategies == rhs.strategies))
    return false;
  if (!(accounts == rhs.accounts))
    return false;
  return true;
}

ListStrategyResponse::ListStrategyResponse(const ListStrategyResponse& other62) {
  status = other62.status;
  detail = other62.detail;
  unitName = other62.unitName;
  strategies = other62.strategies;
  accounts = other62.accounts;
  __isset = other62.__isset;
}
ListStrategyResponse& ListStrategyResponse::operator=(const ListStrategyResponse& other63) {
  status = other63.status;
  detail = other63.detail;
  unitName = other63.unitName;
  strategies = other63.strategies;
  accounts = other63.accounts;
  __isset = other63.__isset;
  return *this;
}
void ListStrategyResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListStrategyResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "unitName=" << to_string(unitName);
  out << ", " << "strategies=" << to_string(strategies);
  out << ", " << "accounts=" << to_string(accounts);
  out << ")";
}


StartStrategyRequest::~StartStrategyRequest() noexcept {
}

StartStrategyRequest::StartStrategyRequest() noexcept
   : unitName(),
     strategyName(),
     mode(static_cast<StrategyTradingMode::type>(0)) {
}

void StartStrategyRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void StartStrategyRequest::__set_strategyName(const std::string& val) {
  this->strategyName = val;
}

void StartStrategyRequest::__set_mode(const StrategyTradingMode::type val) {
  this->mode = val;
}
std::ostream& operator<<(std::ostream& out, const StartStrategyRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StartStrategyRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->strategyName);
          this->__isset.strategyName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast64;
          xfer += iprot->readI32(ecast64);
          this->mode = static_cast<StrategyTradingMode::type>(ecast64);
          this->__isset.mode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StartStrategyRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StartStrategyRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("strategyName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->strategyName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("mode", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(static_cast<int32_t>(this->mode));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StartStrategyRequest &a, StartStrategyRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.strategyName, b.strategyName);
  swap(a.mode, b.mode);
  swap(a.__isset, b.__isset);
}

bool StartStrategyRequest::operator==(const StartStrategyRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  if (!(strategyName == rhs.strategyName))
    return false;
  if (!(mode == rhs.mode))
    return false;
  return true;
}

StartStrategyRequest::StartStrategyRequest(const StartStrategyRequest& other65) {
  unitName = other65.unitName;
  strategyName = other65.strategyName;
  mode = other65.mode;
  __isset = other65.__isset;
}
StartStrategyRequest& StartStrategyRequest::operator=(const StartStrategyRequest& other66) {
  unitName = other66.unitName;
  strategyName = other66.strategyName;
  mode = other66.mode;
  __isset = other66.__isset;
  return *this;
}
void StartStrategyRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StartStrategyRequest(";
  out << "unitName=" << to_string(unitName);
  out << ", " << "strategyName=" << to_string(strategyName);
  out << ", " << "mode=" << to_string(mode);
  out << ")";
}


StartStrategyResponse::~StartStrategyResponse() noexcept {
}

StartStrategyResponse::StartStrategyResponse() noexcept
   : status(0),
     detail() {
}

void StartStrategyResponse::__set_status(const int32_t val) {
  this->status = val;
}

void StartStrategyResponse::__set_detail(const std::string& val) {
  this->detail = val;
}
std::ostream& operator<<(std::ostream& out, const StartStrategyResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StartStrategyResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StartStrategyResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StartStrategyResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StartStrategyResponse &a, StartStrategyResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.__isset, b.__isset);
}

bool StartStrategyResponse::operator==(const StartStrategyResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  return true;
}

StartStrategyResponse::StartStrategyResponse(const StartStrategyResponse& other67) {
  status = other67.status;
  detail = other67.detail;
  __isset = other67.__isset;
}
StartStrategyResponse& StartStrategyResponse::operator=(const StartStrategyResponse& other68) {
  status = other68.status;
  detail = other68.detail;
  __isset = other68.__isset;
  return *this;
}
void StartStrategyResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StartStrategyResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ")";
}


StopStrategyRequest::~StopStrategyRequest() noexcept {
}

StopStrategyRequest::StopStrategyRequest() noexcept
   : unitName(),
     strategyName(),
     mode(static_cast<StrategyTradingMode::type>(0)) {
}

void StopStrategyRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void StopStrategyRequest::__set_strategyName(const std::string& val) {
  this->strategyName = val;
}

void StopStrategyRequest::__set_mode(const StrategyTradingMode::type val) {
  this->mode = val;
}
std::ostream& operator<<(std::ostream& out, const StopStrategyRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StopStrategyRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->strategyName);
          this->__isset.strategyName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast69;
          xfer += iprot->readI32(ecast69);
          this->mode = static_cast<StrategyTradingMode::type>(ecast69);
          this->__isset.mode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StopStrategyRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StopStrategyRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("strategyName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->strategyName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("mode", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(static_cast<int32_t>(this->mode));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StopStrategyRequest &a, StopStrategyRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.strategyName, b.strategyName);
  swap(a.mode, b.mode);
  swap(a.__isset, b.__isset);
}

bool StopStrategyRequest::operator==(const StopStrategyRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  if (!(strategyName == rhs.strategyName))
    return false;
  if (!(mode == rhs.mode))
    return false;
  return true;
}

StopStrategyRequest::StopStrategyRequest(const StopStrategyRequest& other70) {
  unitName = other70.unitName;
  strategyName = other70.strategyName;
  mode = other70.mode;
  __isset = other70.__isset;
}
StopStrategyRequest& StopStrategyRequest::operator=(const StopStrategyRequest& other71) {
  unitName = other71.unitName;
  strategyName = other71.strategyName;
  mode = other71.mode;
  __isset = other71.__isset;
  return *this;
}
void StopStrategyRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StopStrategyRequest(";
  out << "unitName=" << to_string(unitName);
  out << ", " << "strategyName=" << to_string(strategyName);
  out << ", " << "mode=" << to_string(mode);
  out << ")";
}


StopStrategyResponse::~StopStrategyResponse() noexcept {
}

StopStrategyResponse::StopStrategyResponse() noexcept
   : status(0),
     detail() {
}

void StopStrategyResponse::__set_status(const int32_t val) {
  this->status = val;
}

void StopStrategyResponse::__set_detail(const std::string& val) {
  this->detail = val;
}
std::ostream& operator<<(std::ostream& out, const StopStrategyResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StopStrategyResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StopStrategyResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StopStrategyResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StopStrategyResponse &a, StopStrategyResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.__isset, b.__isset);
}

bool StopStrategyResponse::operator==(const StopStrategyResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  return true;
}

StopStrategyResponse::StopStrategyResponse(const StopStrategyResponse& other72) {
  status = other72.status;
  detail = other72.detail;
  __isset = other72.__isset;
}
StopStrategyResponse& StopStrategyResponse::operator=(const StopStrategyResponse& other73) {
  status = other73.status;
  detail = other73.detail;
  __isset = other73.__isset;
  return *this;
}
void StopStrategyResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StopStrategyResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ")";
}


