/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef strategy_TYPES_H
#define strategy_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




struct StrategyTradingMode {
  enum type {
    UNKNOWN = 0,
    TAKING = 1,
    MAKING = 2,
    TRADING = 3
  };
};

extern const std::map<int, const char*> _StrategyTradingMode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const StrategyTradingMode::type& val);

std::string to_string(const StrategyTradingMode::type& val);

class ListStrategyRequest;

class LegInfo;

class RiskInfo;

class AlphaInfo;

class StrategyInfo;

class ListStrategyResponse;

class StartStrategyRequest;

class StartStrategyResponse;

class StopStrategyRequest;

class StopStrategyResponse;

typedef struct _ListStrategyRequest__isset {
  _ListStrategyRequest__isset() : unitName(false) {}
  bool unitName :1;
} _ListStrategyRequest__isset;

class ListStrategyRequest : public virtual ::apache::thrift::TBase {
 public:

  ListStrategyRequest(const ListStrategyRequest&);
  ListStrategyRequest& operator=(const ListStrategyRequest&);
  ListStrategyRequest() noexcept;

  virtual ~ListStrategyRequest() noexcept;
  std::string unitName;

  _ListStrategyRequest__isset __isset;

  void __set_unitName(const std::string& val);

  bool operator == (const ListStrategyRequest & rhs) const;
  bool operator != (const ListStrategyRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListStrategyRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListStrategyRequest &a, ListStrategyRequest &b);

std::ostream& operator<<(std::ostream& out, const ListStrategyRequest& obj);

typedef struct _LegInfo__isset {
  _LegInfo__isset() : name(false), leg(false), future(false), optionChain(false), countFuture(false) {}
  bool name :1;
  bool leg :1;
  bool future :1;
  bool optionChain :1;
  bool countFuture :1;
} _LegInfo__isset;

class LegInfo : public virtual ::apache::thrift::TBase {
 public:

  LegInfo(const LegInfo&);
  LegInfo& operator=(const LegInfo&);
  LegInfo() noexcept;

  virtual ~LegInfo() noexcept;
  std::string name;
  int32_t leg;
  std::string future;
  std::string optionChain;
  bool countFuture;

  _LegInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_leg(const int32_t val);

  void __set_future(const std::string& val);

  void __set_optionChain(const std::string& val);

  void __set_countFuture(const bool val);

  bool operator == (const LegInfo & rhs) const;
  bool operator != (const LegInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LegInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LegInfo &a, LegInfo &b);

std::ostream& operator<<(std::ostream& out, const LegInfo& obj);

typedef struct _RiskInfo__isset {
  _RiskInfo__isset() : name(false), shortcut(false), lpgName(false) {}
  bool name :1;
  bool shortcut :1;
  bool lpgName :1;
} _RiskInfo__isset;

class RiskInfo : public virtual ::apache::thrift::TBase {
 public:

  RiskInfo(const RiskInfo&);
  RiskInfo& operator=(const RiskInfo&);
  RiskInfo() noexcept;

  virtual ~RiskInfo() noexcept;
  std::string name;
  std::string shortcut;
  std::string lpgName;

  _RiskInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_shortcut(const std::string& val);

  void __set_lpgName(const std::string& val);

  bool operator == (const RiskInfo & rhs) const;
  bool operator != (const RiskInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RiskInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RiskInfo &a, RiskInfo &b);

std::ostream& operator<<(std::ostream& out, const RiskInfo& obj);

typedef struct _AlphaInfo__isset {
  _AlphaInfo__isset() : id(false), name(false), lpgName(false) {}
  bool id :1;
  bool name :1;
  bool lpgName :1;
} _AlphaInfo__isset;

class AlphaInfo : public virtual ::apache::thrift::TBase {
 public:

  AlphaInfo(const AlphaInfo&);
  AlphaInfo& operator=(const AlphaInfo&);
  AlphaInfo() noexcept;

  virtual ~AlphaInfo() noexcept;
  int32_t id;
  std::string name;
  std::string lpgName;

  _AlphaInfo__isset __isset;

  void __set_id(const int32_t val);

  void __set_name(const std::string& val);

  void __set_lpgName(const std::string& val);

  bool operator == (const AlphaInfo & rhs) const;
  bool operator != (const AlphaInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AlphaInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AlphaInfo &a, AlphaInfo &b);

std::ostream& operator<<(std::ostream& out, const AlphaInfo& obj);

typedef struct _StrategyInfo__isset {
  _StrategyInfo__isset() : name(false), attributes(false), legs(false), risks(false), alphas(false), topics(false), extraLpgs(false) {}
  bool name :1;
  bool attributes :1;
  bool legs :1;
  bool risks :1;
  bool alphas :1;
  bool topics :1;
  bool extraLpgs :1;
} _StrategyInfo__isset;

class StrategyInfo : public virtual ::apache::thrift::TBase {
 public:

  StrategyInfo(const StrategyInfo&);
  StrategyInfo& operator=(const StrategyInfo&);
  StrategyInfo() noexcept;

  virtual ~StrategyInfo() noexcept;
  std::string name;
  std::map<std::string, std::string>  attributes;
  std::vector<LegInfo>  legs;
  std::vector<RiskInfo>  risks;
  std::vector<AlphaInfo>  alphas;
  std::map<std::string, int32_t>  topics;
  std::vector<std::string>  extraLpgs;

  _StrategyInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_attributes(const std::map<std::string, std::string> & val);

  void __set_legs(const std::vector<LegInfo> & val);

  void __set_risks(const std::vector<RiskInfo> & val);

  void __set_alphas(const std::vector<AlphaInfo> & val);

  void __set_topics(const std::map<std::string, int32_t> & val);

  void __set_extraLpgs(const std::vector<std::string> & val);

  bool operator == (const StrategyInfo & rhs) const;
  bool operator != (const StrategyInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StrategyInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StrategyInfo &a, StrategyInfo &b);

std::ostream& operator<<(std::ostream& out, const StrategyInfo& obj);

typedef struct _ListStrategyResponse__isset {
  _ListStrategyResponse__isset() : status(false), detail(false), unitName(false), strategies(false) {}
  bool status :1;
  bool detail :1;
  bool unitName :1;
  bool strategies :1;
} _ListStrategyResponse__isset;

class ListStrategyResponse : public virtual ::apache::thrift::TBase {
 public:

  ListStrategyResponse(const ListStrategyResponse&);
  ListStrategyResponse& operator=(const ListStrategyResponse&);
  ListStrategyResponse() noexcept;

  virtual ~ListStrategyResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string unitName;
  std::vector<StrategyInfo>  strategies;

  _ListStrategyResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_unitName(const std::string& val);

  void __set_strategies(const std::vector<StrategyInfo> & val);

  bool operator == (const ListStrategyResponse & rhs) const;
  bool operator != (const ListStrategyResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListStrategyResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListStrategyResponse &a, ListStrategyResponse &b);

std::ostream& operator<<(std::ostream& out, const ListStrategyResponse& obj);

typedef struct _StartStrategyRequest__isset {
  _StartStrategyRequest__isset() : unitName(false), strategyName(false), mode(false) {}
  bool unitName :1;
  bool strategyName :1;
  bool mode :1;
} _StartStrategyRequest__isset;

class StartStrategyRequest : public virtual ::apache::thrift::TBase {
 public:

  StartStrategyRequest(const StartStrategyRequest&);
  StartStrategyRequest& operator=(const StartStrategyRequest&);
  StartStrategyRequest() noexcept;

  virtual ~StartStrategyRequest() noexcept;
  std::string unitName;
  std::string strategyName;
  /**
   * 
   * @see StrategyTradingMode
   */
  StrategyTradingMode::type mode;

  _StartStrategyRequest__isset __isset;

  void __set_unitName(const std::string& val);

  void __set_strategyName(const std::string& val);

  void __set_mode(const StrategyTradingMode::type val);

  bool operator == (const StartStrategyRequest & rhs) const;
  bool operator != (const StartStrategyRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StartStrategyRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StartStrategyRequest &a, StartStrategyRequest &b);

std::ostream& operator<<(std::ostream& out, const StartStrategyRequest& obj);

typedef struct _StartStrategyResponse__isset {
  _StartStrategyResponse__isset() : status(false), detail(false) {}
  bool status :1;
  bool detail :1;
} _StartStrategyResponse__isset;

class StartStrategyResponse : public virtual ::apache::thrift::TBase {
 public:

  StartStrategyResponse(const StartStrategyResponse&);
  StartStrategyResponse& operator=(const StartStrategyResponse&);
  StartStrategyResponse() noexcept;

  virtual ~StartStrategyResponse() noexcept;
  int32_t status;
  std::string detail;

  _StartStrategyResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  bool operator == (const StartStrategyResponse & rhs) const;
  bool operator != (const StartStrategyResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StartStrategyResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StartStrategyResponse &a, StartStrategyResponse &b);

std::ostream& operator<<(std::ostream& out, const StartStrategyResponse& obj);

typedef struct _StopStrategyRequest__isset {
  _StopStrategyRequest__isset() : unitName(false), strategyName(false), mode(false) {}
  bool unitName :1;
  bool strategyName :1;
  bool mode :1;
} _StopStrategyRequest__isset;

class StopStrategyRequest : public virtual ::apache::thrift::TBase {
 public:

  StopStrategyRequest(const StopStrategyRequest&);
  StopStrategyRequest& operator=(const StopStrategyRequest&);
  StopStrategyRequest() noexcept;

  virtual ~StopStrategyRequest() noexcept;
  std::string unitName;
  std::string strategyName;
  /**
   * 
   * @see StrategyTradingMode
   */
  StrategyTradingMode::type mode;

  _StopStrategyRequest__isset __isset;

  void __set_unitName(const std::string& val);

  void __set_strategyName(const std::string& val);

  void __set_mode(const StrategyTradingMode::type val);

  bool operator == (const StopStrategyRequest & rhs) const;
  bool operator != (const StopStrategyRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StopStrategyRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StopStrategyRequest &a, StopStrategyRequest &b);

std::ostream& operator<<(std::ostream& out, const StopStrategyRequest& obj);

typedef struct _StopStrategyResponse__isset {
  _StopStrategyResponse__isset() : status(false), detail(false) {}
  bool status :1;
  bool detail :1;
} _StopStrategyResponse__isset;

class StopStrategyResponse : public virtual ::apache::thrift::TBase {
 public:

  StopStrategyResponse(const StopStrategyResponse&);
  StopStrategyResponse& operator=(const StopStrategyResponse&);
  StopStrategyResponse() noexcept;

  virtual ~StopStrategyResponse() noexcept;
  int32_t status;
  std::string detail;

  _StopStrategyResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  bool operator == (const StopStrategyResponse & rhs) const;
  bool operator != (const StopStrategyResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StopStrategyResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StopStrategyResponse &a, StopStrategyResponse &b);

std::ostream& operator<<(std::ostream& out, const StopStrategyResponse& obj);



#endif
