/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "strategy_constants.h"



const strategyConstants g_strategy_constants;

strategyConstants::strategyConstants() {
  WMESSAGE_MONITOR_LIST_STRATEGY = 5121;

  WMESSAGE_MONITOR_START_STRATEGY = 5122;

  WMESSAGE_MONITOR_STOP_STRATEGY = 5123;

}



