/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef strategy_CONSTANTS_H
#define strategy_CONSTANTS_H

#include "strategy_types.h"



class strategyConstants {
 public:
  strategyConstants();

  int32_t WMESSAGE_MONITOR_LIST_STRATEGY;
  int32_t WMESSAGE_MONITOR_START_STRATEGY;
  int32_t WMESSAGE_MONITOR_STOP_STRATEGY;
};

extern const strategyConstants g_strategy_constants;



#endif
