/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "topic_constants.h"



const topicConstants g_topic_constants;

topicConstants::topicConstants() {
  WMESSAGE_TOPIC_SUBSCRIBE = 6145;

  WMESSAGE_TOPIC_NOTIFY = 6146;

  WMESSAGE_TOPIC_UNSUBSCRIBE = 6147;

  WMESSAGE_TOPIC_SUBSCRIBE_UNIT = 6148;

}



