/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef topic_CONSTANTS_H
#define topic_CONSTANTS_H

#include "topic_types.h"



class topicConstants {
 public:
  topicConstants();

  int32_t WMESSAGE_TOPIC_SUBSCRIBE;
  int32_t WMESSAGE_TOPIC_NOTIFY;
  int32_t WMESSAGE_TOPIC_UNSUBSCRIBE;
  int32_t WMESSAGE_TOPIC_SUBSCRIBE_UNIT;
};

extern const topicConstants g_topic_constants;



#endif
