/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef topic_TYPES_H
#define topic_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class SubscribeRequest;

class EnumDesc;

class FieldDesc;

class TopicInfo;

class SubscribeResponse;

class TopicNotify;

class UnsubscribeRequest;

class UnsubscribeResponse;

class SubscribeUnitRequest;

class SubscribeUnitResponse;

typedef struct _SubscribeRequest__isset {
  _SubscribeRequest__isset() : topicID(false) {}
  bool topicID :1;
} _SubscribeRequest__isset;

class SubscribeRequest : public virtual ::apache::thrift::TBase {
 public:

  SubscribeRequest(const SubscribeRequest&) noexcept;
  SubscribeRequest& operator=(const SubscribeRequest&) noexcept;
  SubscribeRequest() noexcept;

  virtual ~SubscribeRequest() noexcept;
  int32_t topicID;

  _SubscribeRequest__isset __isset;

  void __set_topicID(const int32_t val);

  bool operator == (const SubscribeRequest & rhs) const;
  bool operator != (const SubscribeRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SubscribeRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SubscribeRequest &a, SubscribeRequest &b);

std::ostream& operator<<(std::ostream& out, const SubscribeRequest& obj);

typedef struct _EnumDesc__isset {
  _EnumDesc__isset() : name(false), values(false) {}
  bool name :1;
  bool values :1;
} _EnumDesc__isset;

class EnumDesc : public virtual ::apache::thrift::TBase {
 public:

  EnumDesc(const EnumDesc&);
  EnumDesc& operator=(const EnumDesc&);
  EnumDesc() noexcept;

  virtual ~EnumDesc() noexcept;
  std::string name;
  std::map<std::string, int32_t>  values;

  _EnumDesc__isset __isset;

  void __set_name(const std::string& val);

  void __set_values(const std::map<std::string, int32_t> & val);

  bool operator == (const EnumDesc & rhs) const;
  bool operator != (const EnumDesc &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EnumDesc & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(EnumDesc &a, EnumDesc &b);

std::ostream& operator<<(std::ostream& out, const EnumDesc& obj);

typedef struct _FieldDesc__isset {
  _FieldDesc__isset() : name(false), type(false) {}
  bool name :1;
  bool type :1;
} _FieldDesc__isset;

class FieldDesc : public virtual ::apache::thrift::TBase {
 public:

  FieldDesc(const FieldDesc&);
  FieldDesc& operator=(const FieldDesc&);
  FieldDesc() noexcept;

  virtual ~FieldDesc() noexcept;
  std::string name;
  std::string type;

  _FieldDesc__isset __isset;

  void __set_name(const std::string& val);

  void __set_type(const std::string& val);

  bool operator == (const FieldDesc & rhs) const;
  bool operator != (const FieldDesc &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FieldDesc & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(FieldDesc &a, FieldDesc &b);

std::ostream& operator<<(std::ostream& out, const FieldDesc& obj);

typedef struct _TopicInfo__isset {
  _TopicInfo__isset() : name(false), topicID(false), fields(false), enums(false) {}
  bool name :1;
  bool topicID :1;
  bool fields :1;
  bool enums :1;
} _TopicInfo__isset;

class TopicInfo : public virtual ::apache::thrift::TBase {
 public:

  TopicInfo(const TopicInfo&);
  TopicInfo& operator=(const TopicInfo&);
  TopicInfo() noexcept;

  virtual ~TopicInfo() noexcept;
  std::string name;
  int32_t topicID;
  std::vector<FieldDesc>  fields;
  std::map<std::string, EnumDesc>  enums;

  _TopicInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_topicID(const int32_t val);

  void __set_fields(const std::vector<FieldDesc> & val);

  void __set_enums(const std::map<std::string, EnumDesc> & val);

  bool operator == (const TopicInfo & rhs) const;
  bool operator != (const TopicInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TopicInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TopicInfo &a, TopicInfo &b);

std::ostream& operator<<(std::ostream& out, const TopicInfo& obj);

typedef struct _SubscribeResponse__isset {
  _SubscribeResponse__isset() : status(false), detail(false), info(false) {}
  bool status :1;
  bool detail :1;
  bool info :1;
} _SubscribeResponse__isset;

class SubscribeResponse : public virtual ::apache::thrift::TBase {
 public:

  SubscribeResponse(const SubscribeResponse&);
  SubscribeResponse& operator=(const SubscribeResponse&);
  SubscribeResponse() noexcept;

  virtual ~SubscribeResponse() noexcept;
  int32_t status;
  std::string detail;
  TopicInfo info;

  _SubscribeResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_info(const TopicInfo& val);

  bool operator == (const SubscribeResponse & rhs) const;
  bool operator != (const SubscribeResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SubscribeResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SubscribeResponse &a, SubscribeResponse &b);

std::ostream& operator<<(std::ostream& out, const SubscribeResponse& obj);

typedef struct _TopicNotify__isset {
  _TopicNotify__isset() : topicID(false), count(false) {}
  bool topicID :1;
  bool count :1;
} _TopicNotify__isset;

class TopicNotify : public virtual ::apache::thrift::TBase {
 public:

  TopicNotify(const TopicNotify&) noexcept;
  TopicNotify& operator=(const TopicNotify&) noexcept;
  TopicNotify() noexcept;

  virtual ~TopicNotify() noexcept;
  int32_t topicID;
  int32_t count;

  _TopicNotify__isset __isset;

  void __set_topicID(const int32_t val);

  void __set_count(const int32_t val);

  bool operator == (const TopicNotify & rhs) const;
  bool operator != (const TopicNotify &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TopicNotify & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TopicNotify &a, TopicNotify &b);

std::ostream& operator<<(std::ostream& out, const TopicNotify& obj);

typedef struct _UnsubscribeRequest__isset {
  _UnsubscribeRequest__isset() : topicID(false) {}
  bool topicID :1;
} _UnsubscribeRequest__isset;

class UnsubscribeRequest : public virtual ::apache::thrift::TBase {
 public:

  UnsubscribeRequest(const UnsubscribeRequest&) noexcept;
  UnsubscribeRequest& operator=(const UnsubscribeRequest&) noexcept;
  UnsubscribeRequest() noexcept;

  virtual ~UnsubscribeRequest() noexcept;
  int32_t topicID;

  _UnsubscribeRequest__isset __isset;

  void __set_topicID(const int32_t val);

  bool operator == (const UnsubscribeRequest & rhs) const;
  bool operator != (const UnsubscribeRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UnsubscribeRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(UnsubscribeRequest &a, UnsubscribeRequest &b);

std::ostream& operator<<(std::ostream& out, const UnsubscribeRequest& obj);

typedef struct _UnsubscribeResponse__isset {
  _UnsubscribeResponse__isset() : topicID(false), status(false), detail(false) {}
  bool topicID :1;
  bool status :1;
  bool detail :1;
} _UnsubscribeResponse__isset;

class UnsubscribeResponse : public virtual ::apache::thrift::TBase {
 public:

  UnsubscribeResponse(const UnsubscribeResponse&);
  UnsubscribeResponse& operator=(const UnsubscribeResponse&);
  UnsubscribeResponse() noexcept;

  virtual ~UnsubscribeResponse() noexcept;
  int32_t topicID;
  int32_t status;
  std::string detail;

  _UnsubscribeResponse__isset __isset;

  void __set_topicID(const int32_t val);

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  bool operator == (const UnsubscribeResponse & rhs) const;
  bool operator != (const UnsubscribeResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UnsubscribeResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(UnsubscribeResponse &a, UnsubscribeResponse &b);

std::ostream& operator<<(std::ostream& out, const UnsubscribeResponse& obj);

typedef struct _SubscribeUnitRequest__isset {
  _SubscribeUnitRequest__isset() : unitName(false) {}
  bool unitName :1;
} _SubscribeUnitRequest__isset;

class SubscribeUnitRequest : public virtual ::apache::thrift::TBase {
 public:

  SubscribeUnitRequest(const SubscribeUnitRequest&);
  SubscribeUnitRequest& operator=(const SubscribeUnitRequest&);
  SubscribeUnitRequest() noexcept;

  virtual ~SubscribeUnitRequest() noexcept;
  std::string unitName;

  _SubscribeUnitRequest__isset __isset;

  void __set_unitName(const std::string& val);

  bool operator == (const SubscribeUnitRequest & rhs) const;
  bool operator != (const SubscribeUnitRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SubscribeUnitRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SubscribeUnitRequest &a, SubscribeUnitRequest &b);

std::ostream& operator<<(std::ostream& out, const SubscribeUnitRequest& obj);

typedef struct _SubscribeUnitResponse__isset {
  _SubscribeUnitResponse__isset() : status(false), detail(false), unitName(false), infos(false) {}
  bool status :1;
  bool detail :1;
  bool unitName :1;
  bool infos :1;
} _SubscribeUnitResponse__isset;

class SubscribeUnitResponse : public virtual ::apache::thrift::TBase {
 public:

  SubscribeUnitResponse(const SubscribeUnitResponse&);
  SubscribeUnitResponse& operator=(const SubscribeUnitResponse&);
  SubscribeUnitResponse() noexcept;

  virtual ~SubscribeUnitResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string unitName;
  std::vector<TopicInfo>  infos;

  _SubscribeUnitResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_unitName(const std::string& val);

  void __set_infos(const std::vector<TopicInfo> & val);

  bool operator == (const SubscribeUnitResponse & rhs) const;
  bool operator != (const SubscribeUnitResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SubscribeUnitResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SubscribeUnitResponse &a, SubscribeUnitResponse &b);

std::ostream& operator<<(std::ostream& out, const SubscribeUnitResponse& obj);



#endif
