/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "unit_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




ListUnitsRequest::~ListUnitsRequest() noexcept {
}

ListUnitsRequest::ListUnitsRequest() noexcept
   : hostname() {
}

void ListUnitsRequest::__set_hostname(const std::string& val) {
  this->hostname = val;
}
std::ostream& operator<<(std::ostream& out, const ListUnitsRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListUnitsRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->hostname);
          this->__isset.hostname = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListUnitsRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListUnitsRequest");

  xfer += oprot->writeFieldBegin("hostname", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->hostname);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListUnitsRequest &a, ListUnitsRequest &b) {
  using ::std::swap;
  swap(a.hostname, b.hostname);
  swap(a.__isset, b.__isset);
}

bool ListUnitsRequest::operator==(const ListUnitsRequest & rhs) const
{
  if (!(hostname == rhs.hostname))
    return false;
  return true;
}

ListUnitsRequest::ListUnitsRequest(const ListUnitsRequest& other0) {
  hostname = other0.hostname;
  __isset = other0.__isset;
}
ListUnitsRequest& ListUnitsRequest::operator=(const ListUnitsRequest& other1) {
  hostname = other1.hostname;
  __isset = other1.__isset;
  return *this;
}
void ListUnitsRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListUnitsRequest(";
  out << "hostname=" << to_string(hostname);
  out << ")";
}


UnitInfo::~UnitInfo() noexcept {
}

UnitInfo::UnitInfo() noexcept
   : name(),
     type() {
}

void UnitInfo::__set_name(const std::string& val) {
  this->name = val;
}

void UnitInfo::__set_type(const std::string& val) {
  this->type = val;
}
std::ostream& operator<<(std::ostream& out, const UnitInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t UnitInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->type);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t UnitInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("UnitInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(UnitInfo &a, UnitInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.__isset, b.__isset);
}

bool UnitInfo::operator==(const UnitInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(type == rhs.type))
    return false;
  return true;
}

UnitInfo::UnitInfo(const UnitInfo& other2) {
  name = other2.name;
  type = other2.type;
  __isset = other2.__isset;
}
UnitInfo& UnitInfo::operator=(const UnitInfo& other3) {
  name = other3.name;
  type = other3.type;
  __isset = other3.__isset;
  return *this;
}
void UnitInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "UnitInfo(";
  out << "name=" << to_string(name);
  out << ", " << "type=" << to_string(type);
  out << ")";
}


ListUnitsResponse::~ListUnitsResponse() noexcept {
}

ListUnitsResponse::ListUnitsResponse() noexcept
   : status(0),
     detail(),
     hostname() {
}

void ListUnitsResponse::__set_status(const int32_t val) {
  this->status = val;
}

void ListUnitsResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void ListUnitsResponse::__set_hostname(const std::string& val) {
  this->hostname = val;
}

void ListUnitsResponse::__set_units(const std::vector<UnitInfo> & val) {
  this->units = val;
}
std::ostream& operator<<(std::ostream& out, const ListUnitsResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListUnitsResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->hostname);
          this->__isset.hostname = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->units.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->units.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->units[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.units = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ListUnitsResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListUnitsResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("hostname", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->hostname);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("units", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->units.size()));
    std::vector<UnitInfo> ::const_iterator _iter9;
    for (_iter9 = this->units.begin(); _iter9 != this->units.end(); ++_iter9)
    {
      xfer += (*_iter9).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListUnitsResponse &a, ListUnitsResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.hostname, b.hostname);
  swap(a.units, b.units);
  swap(a.__isset, b.__isset);
}

bool ListUnitsResponse::operator==(const ListUnitsResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(hostname == rhs.hostname))
    return false;
  if (!(units == rhs.units))
    return false;
  return true;
}

ListUnitsResponse::ListUnitsResponse(const ListUnitsResponse& other10) {
  status = other10.status;
  detail = other10.detail;
  hostname = other10.hostname;
  units = other10.units;
  __isset = other10.__isset;
}
ListUnitsResponse& ListUnitsResponse::operator=(const ListUnitsResponse& other11) {
  status = other11.status;
  detail = other11.detail;
  hostname = other11.hostname;
  units = other11.units;
  __isset = other11.__isset;
  return *this;
}
void ListUnitsResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListUnitsResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "hostname=" << to_string(hostname);
  out << ", " << "units=" << to_string(units);
  out << ")";
}


