/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "unit_constants.h"



const unitConstants g_unit_constants;

unitConstants::unitConstants() {
  WMESSAGE_MONITOR_UNIT_LIST = 4097;

}



