/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef unit_TYPES_H
#define unit_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class ListUnitsRequest;

class UnitInfo;

class ListUnitsResponse;

typedef struct _ListUnitsRequest__isset {
  _ListUnitsRequest__isset() : hostname(false) {}
  bool hostname :1;
} _ListUnitsRequest__isset;

class ListUnitsRequest : public virtual ::apache::thrift::TBase {
 public:

  ListUnitsRequest(const ListUnitsRequest&);
  ListUnitsRequest& operator=(const ListUnitsRequest&);
  ListUnitsRequest() noexcept;

  virtual ~ListUnitsRequest() noexcept;
  std::string hostname;

  _ListUnitsRequest__isset __isset;

  void __set_hostname(const std::string& val);

  bool operator == (const ListUnitsRequest & rhs) const;
  bool operator != (const ListUnitsRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListUnitsRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListUnitsRequest &a, ListUnitsRequest &b);

std::ostream& operator<<(std::ostream& out, const ListUnitsRequest& obj);

typedef struct _UnitInfo__isset {
  _UnitInfo__isset() : name(false), type(false) {}
  bool name :1;
  bool type :1;
} _UnitInfo__isset;

class UnitInfo : public virtual ::apache::thrift::TBase {
 public:

  UnitInfo(const UnitInfo&);
  UnitInfo& operator=(const UnitInfo&);
  UnitInfo() noexcept;

  virtual ~UnitInfo() noexcept;
  std::string name;
  std::string type;

  _UnitInfo__isset __isset;

  void __set_name(const std::string& val);

  void __set_type(const std::string& val);

  bool operator == (const UnitInfo & rhs) const;
  bool operator != (const UnitInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UnitInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(UnitInfo &a, UnitInfo &b);

std::ostream& operator<<(std::ostream& out, const UnitInfo& obj);

typedef struct _ListUnitsResponse__isset {
  _ListUnitsResponse__isset() : status(false), detail(false), hostname(false), units(false) {}
  bool status :1;
  bool detail :1;
  bool hostname :1;
  bool units :1;
} _ListUnitsResponse__isset;

class ListUnitsResponse : public virtual ::apache::thrift::TBase {
 public:

  ListUnitsResponse(const ListUnitsResponse&);
  ListUnitsResponse& operator=(const ListUnitsResponse&);
  ListUnitsResponse() noexcept;

  virtual ~ListUnitsResponse() noexcept;
  int32_t status;
  std::string detail;
  std::string hostname;
  std::vector<UnitInfo>  units;

  _ListUnitsResponse__isset __isset;

  void __set_status(const int32_t val);

  void __set_detail(const std::string& val);

  void __set_hostname(const std::string& val);

  void __set_units(const std::vector<UnitInfo> & val);

  bool operator == (const ListUnitsResponse & rhs) const;
  bool operator != (const ListUnitsResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListUnitsResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListUnitsResponse &a, ListUnitsResponse &b);

std::ostream& operator<<(std::ostream& out, const ListUnitsResponse& obj);



#endif
