/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef common_CONSTANTS_H
#define common_CONSTANTS_H

#include "common_types.h"



class commonConstants {
 public:
  commonConstants();

  int32_t WMESSAGE_COMMON_HEARTBEAT;
  int32_t WMESSAGE_COMMON_CHECK_TOKEN;
};

extern const commonConstants g_common_constants;



#endif
