/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "common_constants.h"



const commonConstants g_common_constants;

commonConstants::commonConstants() {
  WMESSAGE_COMMON_HEARTBEAT = 1025;

  WMESSAGE_COMMON_CHECK_TOKEN = 1026;

}



