/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "common_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




HeartbeatRequest::~HeartbeatRequest() noexcept {
}

HeartbeatRequest::HeartbeatRequest() noexcept
   : timestamp(0) {
}

void HeartbeatRequest::__set_timestamp(const int64_t val) {
  this->timestamp = val;
}
std::ostream& operator<<(std::ostream& out, const HeartbeatRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t HeartbeatRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timestamp);
          this->__isset.timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HeartbeatRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("HeartbeatRequest");

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(HeartbeatRequest &a, HeartbeatRequest &b) {
  using ::std::swap;
  swap(a.timestamp, b.timestamp);
  swap(a.__isset, b.__isset);
}

bool HeartbeatRequest::operator==(const HeartbeatRequest & rhs) const
{
  if (!(timestamp == rhs.timestamp))
    return false;
  return true;
}

HeartbeatRequest::HeartbeatRequest(const HeartbeatRequest& other0) noexcept {
  timestamp = other0.timestamp;
  __isset = other0.__isset;
}
HeartbeatRequest& HeartbeatRequest::operator=(const HeartbeatRequest& other1) noexcept {
  timestamp = other1.timestamp;
  __isset = other1.__isset;
  return *this;
}
void HeartbeatRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "HeartbeatRequest(";
  out << "timestamp=" << to_string(timestamp);
  out << ")";
}


HeartbeatResponse::~HeartbeatResponse() noexcept {
}

HeartbeatResponse::HeartbeatResponse() noexcept
   : timestamp(0) {
}

void HeartbeatResponse::__set_timestamp(const int64_t val) {
  this->timestamp = val;
}
std::ostream& operator<<(std::ostream& out, const HeartbeatResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t HeartbeatResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timestamp);
          this->__isset.timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HeartbeatResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("HeartbeatResponse");

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(HeartbeatResponse &a, HeartbeatResponse &b) {
  using ::std::swap;
  swap(a.timestamp, b.timestamp);
  swap(a.__isset, b.__isset);
}

bool HeartbeatResponse::operator==(const HeartbeatResponse & rhs) const
{
  if (!(timestamp == rhs.timestamp))
    return false;
  return true;
}

HeartbeatResponse::HeartbeatResponse(const HeartbeatResponse& other2) noexcept {
  timestamp = other2.timestamp;
  __isset = other2.__isset;
}
HeartbeatResponse& HeartbeatResponse::operator=(const HeartbeatResponse& other3) noexcept {
  timestamp = other3.timestamp;
  __isset = other3.__isset;
  return *this;
}
void HeartbeatResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "HeartbeatResponse(";
  out << "timestamp=" << to_string(timestamp);
  out << ")";
}


CheckTokenRequest::~CheckTokenRequest() noexcept {
}

CheckTokenRequest::CheckTokenRequest() noexcept
   : token() {
}

void CheckTokenRequest::__set_token(const std::string& val) {
  this->token = val;
}
std::ostream& operator<<(std::ostream& out, const CheckTokenRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CheckTokenRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->token);
          this->__isset.token = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CheckTokenRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CheckTokenRequest");

  xfer += oprot->writeFieldBegin("token", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->token);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CheckTokenRequest &a, CheckTokenRequest &b) {
  using ::std::swap;
  swap(a.token, b.token);
  swap(a.__isset, b.__isset);
}

bool CheckTokenRequest::operator==(const CheckTokenRequest & rhs) const
{
  if (!(token == rhs.token))
    return false;
  return true;
}

CheckTokenRequest::CheckTokenRequest(const CheckTokenRequest& other4) {
  token = other4.token;
  __isset = other4.__isset;
}
CheckTokenRequest& CheckTokenRequest::operator=(const CheckTokenRequest& other5) {
  token = other5.token;
  __isset = other5.__isset;
  return *this;
}
void CheckTokenRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CheckTokenRequest(";
  out << "token=" << to_string(token);
  out << ")";
}


CheckTokenResponse::~CheckTokenResponse() noexcept {
}

CheckTokenResponse::CheckTokenResponse() noexcept
   : status(0),
     detail(),
     token() {
}

void CheckTokenResponse::__set_status(const int32_t val) {
  this->status = val;
}

void CheckTokenResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void CheckTokenResponse::__set_token(const std::string& val) {
  this->token = val;
}

void CheckTokenResponse::__set_permissions(const std::vector<std::string> & val) {
  this->permissions = val;
}
std::ostream& operator<<(std::ostream& out, const CheckTokenResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CheckTokenResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->token);
          this->__isset.token = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->permissions.clear();
            uint32_t _size6;
            ::apache::thrift::protocol::TType _etype9;
            xfer += iprot->readListBegin(_etype9, _size6);
            this->permissions.resize(_size6);
            uint32_t _i10;
            for (_i10 = 0; _i10 < _size6; ++_i10)
            {
              xfer += iprot->readString(this->permissions[_i10]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.permissions = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CheckTokenResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CheckTokenResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("token", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->token);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("permissions", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->permissions.size()));
    std::vector<std::string> ::const_iterator _iter11;
    for (_iter11 = this->permissions.begin(); _iter11 != this->permissions.end(); ++_iter11)
    {
      xfer += oprot->writeString((*_iter11));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CheckTokenResponse &a, CheckTokenResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.token, b.token);
  swap(a.permissions, b.permissions);
  swap(a.__isset, b.__isset);
}

bool CheckTokenResponse::operator==(const CheckTokenResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(token == rhs.token))
    return false;
  if (!(permissions == rhs.permissions))
    return false;
  return true;
}

CheckTokenResponse::CheckTokenResponse(const CheckTokenResponse& other12) {
  status = other12.status;
  detail = other12.detail;
  token = other12.token;
  permissions = other12.permissions;
  __isset = other12.__isset;
}
CheckTokenResponse& CheckTokenResponse::operator=(const CheckTokenResponse& other13) {
  status = other13.status;
  detail = other13.detail;
  token = other13.token;
  permissions = other13.permissions;
  __isset = other13.__isset;
  return *this;
}
void CheckTokenResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CheckTokenResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "token=" << to_string(token);
  out << ", " << "permissions=" << to_string(permissions);
  out << ")";
}


