/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "instrument_constants.h"



const instrumentConstants g_instrument_constants;

instrumentConstants::instrumentConstants() {
  WMESSAGE_MONITOR_LIST_INSTRUMENT = 7169;

  WMESSAGE_MONITOR_LIST_UNIT_INSTRUMENT = 7170;

}



