/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef instrument_CONSTANTS_H
#define instrument_CONSTANTS_H

#include "instrument_types.h"



class instrumentConstants {
 public:
  instrumentConstants();

  int32_t WMESSAGE_MONITOR_LIST_INSTRUMENT;
  int32_t WMESSAGE_MONITOR_LIST_UNIT_INSTRUMENT;
};

extern const instrumentConstants g_instrument_constants;



#endif
