/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "login_constants.h"



const loginConstants g_login_constants;

loginConstants::loginConstants() {
  WMESSAGE_LOGIN_LOGIN = 3073;

}



