/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef login_CONSTANTS_H
#define login_CONSTANTS_H

#include "login_types.h"



class loginConstants {
 public:
  loginConstants();

  int32_t WMESSAGE_LOGIN_LOGIN;
};

extern const loginConstants g_login_constants;



#endif
