/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "topic_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




SubscribeRequest::~SubscribeRequest() noexcept {
}

SubscribeRequest::SubscribeRequest() noexcept
   : topicID(0) {
}

void SubscribeRequest::__set_topicID(const int32_t val) {
  this->topicID = val;
}
std::ostream& operator<<(std::ostream& out, const SubscribeRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SubscribeRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topicID);
          this->__isset.topicID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SubscribeRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SubscribeRequest");

  xfer += oprot->writeFieldBegin("topicID", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->topicID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SubscribeRequest &a, SubscribeRequest &b) {
  using ::std::swap;
  swap(a.topicID, b.topicID);
  swap(a.__isset, b.__isset);
}

bool SubscribeRequest::operator==(const SubscribeRequest & rhs) const
{
  if (!(topicID == rhs.topicID))
    return false;
  return true;
}

SubscribeRequest::SubscribeRequest(const SubscribeRequest& other0) noexcept {
  topicID = other0.topicID;
  __isset = other0.__isset;
}
SubscribeRequest& SubscribeRequest::operator=(const SubscribeRequest& other1) noexcept {
  topicID = other1.topicID;
  __isset = other1.__isset;
  return *this;
}
void SubscribeRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SubscribeRequest(";
  out << "topicID=" << to_string(topicID);
  out << ")";
}


EnumDesc::~EnumDesc() noexcept {
}

EnumDesc::EnumDesc() noexcept
   : name() {
}

void EnumDesc::__set_name(const std::string& val) {
  this->name = val;
}

void EnumDesc::__set_values(const std::map<std::string, int32_t> & val) {
  this->values = val;
}
std::ostream& operator<<(std::ostream& out, const EnumDesc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t EnumDesc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->values.clear();
            uint32_t _size2;
            ::apache::thrift::protocol::TType _ktype3;
            ::apache::thrift::protocol::TType _vtype4;
            xfer += iprot->readMapBegin(_ktype3, _vtype4, _size2);
            uint32_t _i6;
            for (_i6 = 0; _i6 < _size2; ++_i6)
            {
              std::string _key7;
              xfer += iprot->readString(_key7);
              int32_t& _val8 = this->values[_key7];
              xfer += iprot->readI32(_val8);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.values = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t EnumDesc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("EnumDesc");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("values", ::apache::thrift::protocol::T_MAP, 2);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->values.size()));
    std::map<std::string, int32_t> ::const_iterator _iter9;
    for (_iter9 = this->values.begin(); _iter9 != this->values.end(); ++_iter9)
    {
      xfer += oprot->writeString(_iter9->first);
      xfer += oprot->writeI32(_iter9->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(EnumDesc &a, EnumDesc &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.values, b.values);
  swap(a.__isset, b.__isset);
}

bool EnumDesc::operator==(const EnumDesc & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(values == rhs.values))
    return false;
  return true;
}

EnumDesc::EnumDesc(const EnumDesc& other10) {
  name = other10.name;
  values = other10.values;
  __isset = other10.__isset;
}
EnumDesc& EnumDesc::operator=(const EnumDesc& other11) {
  name = other11.name;
  values = other11.values;
  __isset = other11.__isset;
  return *this;
}
void EnumDesc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "EnumDesc(";
  out << "name=" << to_string(name);
  out << ", " << "values=" << to_string(values);
  out << ")";
}


FieldDesc::~FieldDesc() noexcept {
}

FieldDesc::FieldDesc() noexcept
   : name(),
     type() {
}

void FieldDesc::__set_name(const std::string& val) {
  this->name = val;
}

void FieldDesc::__set_type(const std::string& val) {
  this->type = val;
}
std::ostream& operator<<(std::ostream& out, const FieldDesc& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t FieldDesc::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->type);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t FieldDesc::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("FieldDesc");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(FieldDesc &a, FieldDesc &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.__isset, b.__isset);
}

bool FieldDesc::operator==(const FieldDesc & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(type == rhs.type))
    return false;
  return true;
}

FieldDesc::FieldDesc(const FieldDesc& other12) {
  name = other12.name;
  type = other12.type;
  __isset = other12.__isset;
}
FieldDesc& FieldDesc::operator=(const FieldDesc& other13) {
  name = other13.name;
  type = other13.type;
  __isset = other13.__isset;
  return *this;
}
void FieldDesc::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "FieldDesc(";
  out << "name=" << to_string(name);
  out << ", " << "type=" << to_string(type);
  out << ")";
}


TopicInfo::~TopicInfo() noexcept {
}

TopicInfo::TopicInfo() noexcept
   : name(),
     topicID(0) {
}

void TopicInfo::__set_name(const std::string& val) {
  this->name = val;
}

void TopicInfo::__set_topicID(const int32_t val) {
  this->topicID = val;
}

void TopicInfo::__set_fields(const std::vector<FieldDesc> & val) {
  this->fields = val;
}

void TopicInfo::__set_enums(const std::map<std::string, EnumDesc> & val) {
  this->enums = val;
}
std::ostream& operator<<(std::ostream& out, const TopicInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TopicInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topicID);
          this->__isset.topicID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->fields.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _etype17;
            xfer += iprot->readListBegin(_etype17, _size14);
            this->fields.resize(_size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              xfer += this->fields[_i18].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.fields = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->enums.clear();
            uint32_t _size19;
            ::apache::thrift::protocol::TType _ktype20;
            ::apache::thrift::protocol::TType _vtype21;
            xfer += iprot->readMapBegin(_ktype20, _vtype21, _size19);
            uint32_t _i23;
            for (_i23 = 0; _i23 < _size19; ++_i23)
            {
              std::string _key24;
              xfer += iprot->readString(_key24);
              EnumDesc& _val25 = this->enums[_key24];
              xfer += _val25.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.enums = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TopicInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TopicInfo");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("topicID", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->topicID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("fields", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fields.size()));
    std::vector<FieldDesc> ::const_iterator _iter26;
    for (_iter26 = this->fields.begin(); _iter26 != this->fields.end(); ++_iter26)
    {
      xfer += (*_iter26).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("enums", ::apache::thrift::protocol::T_MAP, 4);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->enums.size()));
    std::map<std::string, EnumDesc> ::const_iterator _iter27;
    for (_iter27 = this->enums.begin(); _iter27 != this->enums.end(); ++_iter27)
    {
      xfer += oprot->writeString(_iter27->first);
      xfer += _iter27->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TopicInfo &a, TopicInfo &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.topicID, b.topicID);
  swap(a.fields, b.fields);
  swap(a.enums, b.enums);
  swap(a.__isset, b.__isset);
}

bool TopicInfo::operator==(const TopicInfo & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(topicID == rhs.topicID))
    return false;
  if (!(fields == rhs.fields))
    return false;
  if (!(enums == rhs.enums))
    return false;
  return true;
}

TopicInfo::TopicInfo(const TopicInfo& other28) {
  name = other28.name;
  topicID = other28.topicID;
  fields = other28.fields;
  enums = other28.enums;
  __isset = other28.__isset;
}
TopicInfo& TopicInfo::operator=(const TopicInfo& other29) {
  name = other29.name;
  topicID = other29.topicID;
  fields = other29.fields;
  enums = other29.enums;
  __isset = other29.__isset;
  return *this;
}
void TopicInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TopicInfo(";
  out << "name=" << to_string(name);
  out << ", " << "topicID=" << to_string(topicID);
  out << ", " << "fields=" << to_string(fields);
  out << ", " << "enums=" << to_string(enums);
  out << ")";
}


SubscribeResponse::~SubscribeResponse() noexcept {
}

SubscribeResponse::SubscribeResponse() noexcept
   : status(0),
     detail() {
}

void SubscribeResponse::__set_status(const int32_t val) {
  this->status = val;
}

void SubscribeResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void SubscribeResponse::__set_info(const TopicInfo& val) {
  this->info = val;
}
std::ostream& operator<<(std::ostream& out, const SubscribeResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SubscribeResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->info.read(iprot);
          this->__isset.info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SubscribeResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SubscribeResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("info", ::apache::thrift::protocol::T_STRUCT, 3);
  xfer += this->info.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SubscribeResponse &a, SubscribeResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.info, b.info);
  swap(a.__isset, b.__isset);
}

bool SubscribeResponse::operator==(const SubscribeResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(info == rhs.info))
    return false;
  return true;
}

SubscribeResponse::SubscribeResponse(const SubscribeResponse& other30) {
  status = other30.status;
  detail = other30.detail;
  info = other30.info;
  __isset = other30.__isset;
}
SubscribeResponse& SubscribeResponse::operator=(const SubscribeResponse& other31) {
  status = other31.status;
  detail = other31.detail;
  info = other31.info;
  __isset = other31.__isset;
  return *this;
}
void SubscribeResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SubscribeResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "info=" << to_string(info);
  out << ")";
}


TopicNotify::~TopicNotify() noexcept {
}

TopicNotify::TopicNotify() noexcept
   : topicID(0),
     count(0) {
}

void TopicNotify::__set_topicID(const int32_t val) {
  this->topicID = val;
}

void TopicNotify::__set_count(const int32_t val) {
  this->count = val;
}
std::ostream& operator<<(std::ostream& out, const TopicNotify& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TopicNotify::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topicID);
          this->__isset.topicID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TopicNotify::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TopicNotify");

  xfer += oprot->writeFieldBegin("topicID", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->topicID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TopicNotify &a, TopicNotify &b) {
  using ::std::swap;
  swap(a.topicID, b.topicID);
  swap(a.count, b.count);
  swap(a.__isset, b.__isset);
}

bool TopicNotify::operator==(const TopicNotify & rhs) const
{
  if (!(topicID == rhs.topicID))
    return false;
  if (!(count == rhs.count))
    return false;
  return true;
}

TopicNotify::TopicNotify(const TopicNotify& other32) noexcept {
  topicID = other32.topicID;
  count = other32.count;
  __isset = other32.__isset;
}
TopicNotify& TopicNotify::operator=(const TopicNotify& other33) noexcept {
  topicID = other33.topicID;
  count = other33.count;
  __isset = other33.__isset;
  return *this;
}
void TopicNotify::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TopicNotify(";
  out << "topicID=" << to_string(topicID);
  out << ", " << "count=" << to_string(count);
  out << ")";
}


UnsubscribeRequest::~UnsubscribeRequest() noexcept {
}

UnsubscribeRequest::UnsubscribeRequest() noexcept
   : topicID(0) {
}

void UnsubscribeRequest::__set_topicID(const int32_t val) {
  this->topicID = val;
}
std::ostream& operator<<(std::ostream& out, const UnsubscribeRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t UnsubscribeRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topicID);
          this->__isset.topicID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t UnsubscribeRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("UnsubscribeRequest");

  xfer += oprot->writeFieldBegin("topicID", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->topicID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(UnsubscribeRequest &a, UnsubscribeRequest &b) {
  using ::std::swap;
  swap(a.topicID, b.topicID);
  swap(a.__isset, b.__isset);
}

bool UnsubscribeRequest::operator==(const UnsubscribeRequest & rhs) const
{
  if (!(topicID == rhs.topicID))
    return false;
  return true;
}

UnsubscribeRequest::UnsubscribeRequest(const UnsubscribeRequest& other34) noexcept {
  topicID = other34.topicID;
  __isset = other34.__isset;
}
UnsubscribeRequest& UnsubscribeRequest::operator=(const UnsubscribeRequest& other35) noexcept {
  topicID = other35.topicID;
  __isset = other35.__isset;
  return *this;
}
void UnsubscribeRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "UnsubscribeRequest(";
  out << "topicID=" << to_string(topicID);
  out << ")";
}


UnsubscribeResponse::~UnsubscribeResponse() noexcept {
}

UnsubscribeResponse::UnsubscribeResponse() noexcept
   : topicID(0),
     status(0),
     detail() {
}

void UnsubscribeResponse::__set_topicID(const int32_t val) {
  this->topicID = val;
}

void UnsubscribeResponse::__set_status(const int32_t val) {
  this->status = val;
}

void UnsubscribeResponse::__set_detail(const std::string& val) {
  this->detail = val;
}
std::ostream& operator<<(std::ostream& out, const UnsubscribeResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t UnsubscribeResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topicID);
          this->__isset.topicID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t UnsubscribeResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("UnsubscribeResponse");

  xfer += oprot->writeFieldBegin("topicID", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->topicID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(UnsubscribeResponse &a, UnsubscribeResponse &b) {
  using ::std::swap;
  swap(a.topicID, b.topicID);
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.__isset, b.__isset);
}

bool UnsubscribeResponse::operator==(const UnsubscribeResponse & rhs) const
{
  if (!(topicID == rhs.topicID))
    return false;
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  return true;
}

UnsubscribeResponse::UnsubscribeResponse(const UnsubscribeResponse& other36) {
  topicID = other36.topicID;
  status = other36.status;
  detail = other36.detail;
  __isset = other36.__isset;
}
UnsubscribeResponse& UnsubscribeResponse::operator=(const UnsubscribeResponse& other37) {
  topicID = other37.topicID;
  status = other37.status;
  detail = other37.detail;
  __isset = other37.__isset;
  return *this;
}
void UnsubscribeResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "UnsubscribeResponse(";
  out << "topicID=" << to_string(topicID);
  out << ", " << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ")";
}


SubscribeUnitRequest::~SubscribeUnitRequest() noexcept {
}

SubscribeUnitRequest::SubscribeUnitRequest() noexcept
   : unitName() {
}

void SubscribeUnitRequest::__set_unitName(const std::string& val) {
  this->unitName = val;
}
std::ostream& operator<<(std::ostream& out, const SubscribeUnitRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SubscribeUnitRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SubscribeUnitRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SubscribeUnitRequest");

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SubscribeUnitRequest &a, SubscribeUnitRequest &b) {
  using ::std::swap;
  swap(a.unitName, b.unitName);
  swap(a.__isset, b.__isset);
}

bool SubscribeUnitRequest::operator==(const SubscribeUnitRequest & rhs) const
{
  if (!(unitName == rhs.unitName))
    return false;
  return true;
}

SubscribeUnitRequest::SubscribeUnitRequest(const SubscribeUnitRequest& other38) {
  unitName = other38.unitName;
  __isset = other38.__isset;
}
SubscribeUnitRequest& SubscribeUnitRequest::operator=(const SubscribeUnitRequest& other39) {
  unitName = other39.unitName;
  __isset = other39.__isset;
  return *this;
}
void SubscribeUnitRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SubscribeUnitRequest(";
  out << "unitName=" << to_string(unitName);
  out << ")";
}


SubscribeUnitResponse::~SubscribeUnitResponse() noexcept {
}

SubscribeUnitResponse::SubscribeUnitResponse() noexcept
   : status(0),
     detail(),
     unitName() {
}

void SubscribeUnitResponse::__set_status(const int32_t val) {
  this->status = val;
}

void SubscribeUnitResponse::__set_detail(const std::string& val) {
  this->detail = val;
}

void SubscribeUnitResponse::__set_unitName(const std::string& val) {
  this->unitName = val;
}

void SubscribeUnitResponse::__set_infos(const std::vector<TopicInfo> & val) {
  this->infos = val;
}
std::ostream& operator<<(std::ostream& out, const SubscribeUnitResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SubscribeUnitResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->detail);
          this->__isset.detail = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->unitName);
          this->__isset.unitName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->infos.clear();
            uint32_t _size40;
            ::apache::thrift::protocol::TType _etype43;
            xfer += iprot->readListBegin(_etype43, _size40);
            this->infos.resize(_size40);
            uint32_t _i44;
            for (_i44 = 0; _i44 < _size40; ++_i44)
            {
              xfer += this->infos[_i44].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.infos = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SubscribeUnitResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SubscribeUnitResponse");

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("detail", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->detail);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("unitName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->unitName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("infos", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->infos.size()));
    std::vector<TopicInfo> ::const_iterator _iter45;
    for (_iter45 = this->infos.begin(); _iter45 != this->infos.end(); ++_iter45)
    {
      xfer += (*_iter45).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SubscribeUnitResponse &a, SubscribeUnitResponse &b) {
  using ::std::swap;
  swap(a.status, b.status);
  swap(a.detail, b.detail);
  swap(a.unitName, b.unitName);
  swap(a.infos, b.infos);
  swap(a.__isset, b.__isset);
}

bool SubscribeUnitResponse::operator==(const SubscribeUnitResponse & rhs) const
{
  if (!(status == rhs.status))
    return false;
  if (!(detail == rhs.detail))
    return false;
  if (!(unitName == rhs.unitName))
    return false;
  if (!(infos == rhs.infos))
    return false;
  return true;
}

SubscribeUnitResponse::SubscribeUnitResponse(const SubscribeUnitResponse& other46) {
  status = other46.status;
  detail = other46.detail;
  unitName = other46.unitName;
  infos = other46.infos;
  __isset = other46.__isset;
}
SubscribeUnitResponse& SubscribeUnitResponse::operator=(const SubscribeUnitResponse& other47) {
  status = other47.status;
  detail = other47.detail;
  unitName = other47.unitName;
  infos = other47.infos;
  __isset = other47.__isset;
  return *this;
}
void SubscribeUnitResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SubscribeUnitResponse(";
  out << "status=" << to_string(status);
  out << ", " << "detail=" << to_string(detail);
  out << ", " << "unitName=" << to_string(unitName);
  out << ", " << "infos=" << to_string(infos);
  out << ")";
}


