/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef unit_CONSTANTS_H
#define unit_CONSTANTS_H

#include "unit_types.h"



class unitConstants {
 public:
  unitConstants();

  int32_t WMESSAGE_MONITOR_UNIT_LIST;
};

extern const unitConstants g_unit_constants;



#endif
