SET(PROJECT_NAME "TestServer")
project(${PROJECT_NAME})
message("PROJECT_NAME:" ${PROJECT_NAME})


add_package(Src ./Src)
add_package(TestUtility ${CMAKE_SOURCE_DIR}/Test/Source/TestUtility)
add_package(Packages ${CMAKE_SOURCE_DIR}/Test/Source/Packages)
add_package(Types ${CMAKE_SOURCE_DIR}/Source/Types)
add_package(Fields ${CMAKE_SOURCE_DIR}/Test/Source/Fields)
add_package(Step ${CMAKE_SOURCE_DIR}/Test/Source/Step)
add_package(Xtp ${CMAKE_SOURCE_DIR}/Test/Source/Xtp)
add_package(Platform ${CMAKE_SOURCE_DIR}/Source/Platform)
add_package(Connect ${CMAKE_SOURCE_DIR}/Source/Connect)
add_package(Constant ${CMAKE_SOURCE_DIR}/Source/Constant)
add_package(Utility ${CMAKE_SOURCE_DIR}/Source/Utility)
add_package(MemCache ${CMAKE_SOURCE_DIR}/Source/MemCache)
add_package(ThreadBase ${CMAKE_SOURCE_DIR}/Source/ThreadBase)
add_package(IOThread ${CMAKE_SOURCE_DIR}/Source/IOThread)
add_package(Buffer ${CMAKE_SOURCE_DIR}/Source/Buffer)
add_package(Logger ${CMAKE_SOURCE_DIR}/Source/Logger)
add_package(Encode ${CMAKE_SOURCE_DIR}/Source/Encode)
add_package(SocketInit ${CMAKE_SOURCE_DIR}/Source/SocketInit)
add_package(Timer ${CMAKE_SOURCE_DIR}/Source/Timer)
add_package(TcpBase ${CMAKE_SOURCE_DIR}/Source/Tcp/TcpBase)
add_package(TcpSelect ${CMAKE_SOURCE_DIR}/Source/Tcp/TcpSelect)
add_package(TcpEpoll ${CMAKE_SOURCE_DIR}/Source/Tcp/TcpEpoll)
add_package(Shm ${CMAKE_SOURCE_DIR}/Source/Shm)
add_package(Package ${CMAKE_SOURCE_DIR}/Source/Package)
add_package(Protocol ${CMAKE_SOURCE_DIR}/Source/Protocol)

add_executable(${PROJECT_NAME} ${all_file})
if(CMAKE_SYSTEM_NAME MATCHES "Linux")
	target_link_libraries(${PROJECT_NAME} pthread)
endif()
