SET(PROJECT_NAME "TestCtpApi")
SET(APIVersion "6.7.2")
project(${PROJECT_NAME})
message("PROJECT_NAME:" ${PROJECT_NAME})

add_package(Src ./Src)
add_package(Types ${CMAKE_SOURCE_DIR}/Source/Types)
add_package(Buffer ${CMAKE_SOURCE_DIR}/Source/Buffer)
add_package(Constant ${CMAKE_SOURCE_DIR}/Source/Constant)
add_package(Platform ${CMAKE_SOURCE_DIR}/Source/Platform)
add_package(Utility ${CMAKE_SOURCE_DIR}/Source/Utility)
add_package(MemCache ${CMAKE_SOURCE_DIR}/Source/MemCache)
add_package(ThreadBase ${CMAKE_SOURCE_DIR}/Source/ThreadBase)
add_package(Logger ${CMAKE_SOURCE_DIR}/Source/Logger)
add_package(Jsoncpp ${CMAKE_SOURCE_DIR}/Source/Jsoncpp)
add_package(CtpGenCode ${CMAKE_SOURCE_DIR}/Test/Source/Ctp/${APIVersion})
include_package(Ctp ${CMAKE_SOURCE_DIR}/../Libs/CTP/${APIVersion}/include)

link_directories(${CMAKE_SOURCE_DIR}/../Libs/CTP/${APIVersion}/win64)
add_executable(${PROJECT_NAME} ${all_file})

IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
	target_link_libraries(${PROJECT_NAME} thosttraderapi_se)
elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
	target_link_libraries(${PROJECT_NAME} thosttraderapi_se pthread)
endif()
