version: '1.0'
name: pipeline
displayName: pipeline
triggers:
  trigger: manual
stages:
  - name: stage-c7166dc6
    displayName: Build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: GCC 构建
        gccVersion: 11.1.0
        commands:
          - '# 新建build目录，切换到build目录'
          - 'mkdir build && cd build '
          - '# 生成Unix平台的makefiles文件并执行构建'
          - cmake -G 'Unix Makefiles' ../ && make -j2
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./build/bin
              - ./build/lib
        caches: []
        notify: []
        strategy:
          retry: '0'
